### ISSUE TITLE
Failed serializing enum on extended class

### ISSUE THREAD

**Issue by fidlip** [k-paxian/dart-json-mapper#10]
Given this sample:
```
import 'package:dart_json_mapper/annotations.dart';
import 'package:dart_json_mapper/json_mapper.dart';

import 'main.reflectable.dart';

enum OperationType { insert, update, remove }


@jsonSerializable
class Change {
  String path;
  @JsonProperty(enumValues: OperationType.values)
  OperationType operation;
  Change({this.path, this.operation});
}

@jsonSerializable
class ContentChange extends Change {
  Map<String, dynamic> value;
  ContentChange({String path, OperationType operation, this.value})
      : super(path: path, operation: operation);
}

@jsonSerializable
class UpdateChange extends ContentChange {
  UpdateChange({String path, Map<String, dynamic> item})
      : super(path: path, operation: OperationType.update, value: item);
}

void main() {
  initializeReflectable();

  var change = Change(operation: OperationType.update, path: "info");
  var contentChange = ContentChange(operation: OperationType.update, path: "info", value: {"name": "newName"});
  var updateChange = UpdateChange(path: "info", item: {"name": "newName"});

  // this is OK
  var serialized = JsonMapper.serialize(change);
  print("serialized change:$serialized");

  // this will throw error!!!
  serialized = JsonMapper.serialize(contentChange);
  print("serialized contentChange:$serialized");

  // also error
  serialized = JsonMapper.serialize(updateChange);
  print("serialized updateChange:$serialized");
}

```
This will print:

> serialized change:{
>  "path": "info",
>  "operation": "OperationType.update"
> }
> Unhandled exception:
> It seems your Enum class field is missing annotation:
> @JsonProperty(enumValues: OperationType.values)
> #0      JsonMapper.serializeObject (package:dart_json_mapper/json_mapper.dart:448:9)
> #1      JsonMapper.serializeObject.<anonymous closure> (package:dart_json_mapper/json_mapper.dart:467:28)
> #2      JsonMapper.enumeratePublicFields (package:dart_json_mapper/json_mapper.dart:303:14)
> #3      JsonMapper.serializeObject (package:dart_json_mapper/json_mapper.dart:456:5)
> #4      JsonMapper.serialize (package:dart_json_mapper/json_mapper.dart:48:37)
> #5      main (file:///home/fidlip/dev/wspace/json_mapper_test/bin/main.dart:53:27)
> #6      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
> #7      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
> 
> 
Is it intended to support classes with enums inherited from parent class?

Tested on:
v. 1.6
SDK 2.1.0

**Comment by k-paxian** [comment]
@fidlip 
Thank you so much for your report! Issue fixed.

**Comment by fidlip** [comment]
Thanks a lot!
