### ISSUE TITLE
Naming conflicts in generated file²

### ISSUE THREAD

**Issue by caneva20** [k-paxian/dart-json-mapper#100]
Hi @k-paxian! I'm here bothering you again.

After the fix in #99 I'm facing another issue, not really related though.
I have some classes that share the same name, but are in different packages, and they are both marked with `@jsonSerializable`. As a prefix is not used when using them, this causes naming conflicts.
This is not the same as reported in #88.

### Minimum reproducible code:
* in `lib/a.dart`:
```dart
import 'package:dart_json_mapper/dart_json_mapper.dart';

@jsonSerializable
class Foo {}
```

* in `lib/b.dart`:
```dart
import 'package:dart_json_mapper/dart_json_mapper.dart';

@jsonSerializable
class Foo {}
```

This will cause a naming conflict in `*.mapper.g.dart`

**Comment by k-paxian** [comment]
Cool, love to improve things. Thank you for your support and assistance in investigations.
