### ISSUE TITLE
Deserialization fails when using generic types

### ISSUE THREAD

**Issue by caneva20** [k-paxian/dart-json-mapper#101]
Hello @k-paxian! I'm here once again 😃 

So, given the following models:
```dart
@jsonSerializable
class Foo {}

@jsonSerializable
abstract class BarBase<T> {
  T foo;
}

@jsonSerializable
class Bar extends BarBase<Foo> {}
```

I get the following error when trying to deserialize it:
```shell
Unhandled exception:
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Foo' of 'value'
#0      BarBase.foo= (file:///C:/dev/flutter/json_tests/bin/task.dart)
#1      _data.<anonymous closure> (file:///C:/dev/flutter/json_tests/bin/main.mapper.g.dart:25:3302)
#2      _InstanceMirrorImpl.invokeSetter (package:reflectable/src/reflectable_builder_based.dart:355:20)
#3      JsonMapper._deserializeObject.<anonymous closure> (package:dart_json_mapper/src/mapper.dart:881:12)
#4      JsonMapper._enumeratePublicProperties (package:dart_json_mapper/src/mapper.dart:457:14)
#5      JsonMapper._deserializeObject (package:dart_json_mapper/src/mapper.dart:836:5)
#6      JsonMapper.deserialize (package:dart_json_mapper/src/mapper.dart:62:21)
#7      main (file:///C:/dev/flutter/json_tests/bin/main.dart:12:25)
```

my `main()`:

```dart
void main() {
  initializeJsonMapper();

  var bar = Bar()..foo = Foo();

  var json = JsonMapper.serialize(bar);
  var bar2 = JsonMapper.deserialize<Bar>(json);
}
```

* If I use `var bar = Bar();` it works fine.
* I've tried using a template, but the same thing happens.
* I've tried putting `@Json(typeNameProperty: 'typeName')` on `Foo` and `BarBase`, but it doesn't seem to help.

I understand that what I'm trying to do is kinda weird (why would someone want to do it like that?), and if that is not possible to do (not a bug) that's fine, I'll find an alternative.

**Comment by k-paxian** [comment]
Generics are hard in terms of deserialization 🤷 

Anyway, I've got some examples for you

- This [commit](https://github.com/k-paxian/dart-json-mapper/commit/bc057d0195c01446ff9f1db23ecca9cca710110f) elaborates on your example use case 

- Tuples use case: https://github.com/k-paxian/dart-json-mapper/blob/master/mapper/test/test.tuple.dart

- General generics https://github.com/k-paxian/dart-json-mapper/blob/master/mapper/test/test.generics.dart

Hope this helps somehow 😄

**Comment by masoodmrx** [comment]
Hello @k-paxian

I have the same problem, but the error is different

![image](https://user-images.githubusercontent.com/29932641/148447631-f24c7732-7be6-45ae-9202-d0e05b38c59f.png)
my `main()`
```dart
void main() {
  initializeJsonMapper();
  String json = '{"Success":true,"Result":{"Id":1,"Name":"aa"}}';
  ApiResult<UserModel>? result = JsonMapper.deserialize<ApiResult<UserModel>>(json);

...
}
```

my `models`

```dart
@jsonSerializable
class ApiResult<T> {
  bool? Success;
  T? Result;

  ApiResult({
    this.Success,
    this.Result,
  });

  ApiResult<T>? fromJson(dynamic json) =>
      JsonMapper.deserialize<ApiResult<T>>(json);

  dynamic toJson() =>
      JsonMapper.serialize(this, SerializationOptions(indent: ''));
}

@jsonSerializable
class UserModel {
  int? Id;
  String? Name;

  UserModel({
    this.Id,
    this.Name,
  });
}

@jsonSerializable
@Json(valueDecorators: ApiResultUserModel.valueDecorators)
class ApiResultUserModel extends ApiResult<UserModel> {
  static Map<Type, ValueDecoratorFunction> valueDecorators() =>
      {typeOf<ApiResult<UserModel>>(): (value) => ApiResultUserModel.of(value)};

  ApiResultUserModel({
    bool? Success,
    UserModel? Result,
  }) : super(
          Success: Success,
          Result: Result,
        );

  factory ApiResultUserModel.of(ApiResult other) => ApiResultUserModel(
        Success: other.Success,
        Result: other.Result,
      );
}
```



Serialization is done without errors

The package you produced is very simple and practical compared to other packages 👍

**Comment by k-paxian** [comment]
@masoodmrx Thank you for reporting that, I've got your use case working at [this ](https://github.com/k-paxian/dart-json-mapper/commit/1bf9b75252e3b3f7e14f79c82179aaed526fda3b) commit.

Anyway, the `ApiResultUserModel` class is an obvious overhead to simulate generics support, which makes generics not generics anymore 😞 

I've got a future plan to handle generics in a more clean way, just like [this ](https://github.com/schultek/dart_mappable)copy cat package does, due to lack of time this might be not soon enough 🤷

**Comment by masoodmrx** [comment]
Hello @k-paxian

The error I sent above has not been resolved yet and only gives this error in the browser
Please solve the problem, I need it
Thank you very much ❤️

**Comment by k-paxian** [comment]
With version`2.2.1` and those models below, seems OK now, please confirm on your side.

```dart
@jsonSerializable
class ApiResult<T> {
  bool? Success;
  T? Result;

  ApiResult({
    this.Success,
    this.Result,
  });

  ApiResult<T>? fromJson(dynamic json) =>
      JsonMapper.deserialize<ApiResult<T>>(json);

  dynamic toJson() =>
      JsonMapper.serialize(this, SerializationOptions(indent: ''));
}

@jsonSerializable
class UserModel {
  int? Id;
  String? Name;

  UserModel({
    this.Id,
    this.Name,
  });
}

@jsonSerializable
@Json(valueDecorators: ApiResultUserModel.valueDecorators)
class ApiResultUserModel extends ApiResult<UserModel> {
  static Map<Type, ValueDecoratorFunction> valueDecorators() =>
      {typeOf<ApiResult<UserModel>>(): (value) => ApiResultUserModel.of(value)};

  ApiResultUserModel({
    bool? Success,
    UserModel? Result,
  }) : super(
          Success: Success,
          Result: Result,
        );

  factory ApiResultUserModel.of(ApiResult other) => ApiResultUserModel(
        Success: other.Success,
        Result: JsonMapper.deserialize<UserModel>(other.Result), /// <= Attention: here is the change
      );
}
```

**Comment by masoodmrx** [comment]
Error changed 🤦‍♂️

![image](https://user-images.githubusercontent.com/29932641/148540316-10f75e9a-b266-4c58-a1b4-63756e59a889.png)

**Comment by masoodmrx** [comment]
Error fixed
Thank you very much ❤️
