### ISSUE TITLE
Custom converter results cache layer does not work as expected

### ISSUE THREAD

**Issue by moneer-muntazah** [k-paxian/dart-json-mapper#104]
Hi k-paxian,

Did you remove the cache layer from #86 ? I noticed that with the latest release it doesn't cache. I actually had a little problem with it. My app supports multiple locales, and if the user changes the language some of my dates don't get translated because the the state of the locale is saved outside my date converter, but are use inside it. I was going to change my logic to go around this, but after updating I'm no longer having this issue so I just thought I'll ask you about it.

Thank you

**Comment by k-paxian** [comment]
No, I didn't do anything to intentionally remove caching. I'll put up some unit tests to discover what is going on there.
Could you help me please to define a precise scenario which is not working for you?

**Comment by moneer-muntazah** [comment]
I'm sorry I used this code sample 

```dart
import 'package:dart_json_mapper/dart_json_mapper.dart'
    show
        JsonMapper,
        Json,
        jsonSerializable,
        ICustomConverter,
        JsonProperty,
        SerializationContext,
        DeserializationContext;
import 'main.mapper.g.dart' show initializeJsonMapper;
import "package:meta/meta.dart";

const myCustomConverter = _MyCustomConverter();

class _MyCustomConverter implements ICustomConverter<String> {
  const _MyCustomConverter();

  @override
  String fromJSON(dynamic jsonValue, [JsonProperty context]) {
    print("called");
    if (jsonValue is int) return jsonValue.toString();
    if (jsonValue is String) return jsonValue;
    return null;
  }

  @override
  dynamic toJSON(String object, [JsonProperty context]) {
    throw UnimplementedError();
  }
}

@jsonSerializable
@immutable
class User {
  @JsonProperty(name: "id")
  final int id;

  @JsonProperty(name: "type", converter: myCustomConverter)
  final String type;

  User(this.id, this.type);

  @override
  String toString() {
    return '''{"id": $id, "type": $type}''';
  }
}

void main() {
  initializeJsonMapper();

  User user = JsonMapper.deserialize('''{"id": 42,  "type": "sudoer"}''');

  print(user);

}
```

with 1.7.0 `called` is printed one time, but with 1.7.5 it's printed twice so I assumed that had to do with caching. Prior to 1.7.0 it would've of gotten printed three times. But please don't close this issue yet. I have to check my flutter app, and see why the behavior changed after I updated to latest. I'll check it out on Sunday. 

Thank you very much

**Comment by moneer-muntazah** [comment]
I got my change log a bit mixed. The cache was introduced in 1.6..5 but you know what I mean

**Comment by moneer-muntazah** [comment]
Hi @k-paxian 

Try the above code with 

```dart
void main() {
  initializeJsonMapper();

  JsonMapper.deserialize<User>('''{"id": 42,  "type": "sudoer"}''');

  JsonMapper.deserialize<User>('''{"id": 42,  "type": "sudoer"}''');
}
```

With version `1.7.0` the converter gets called a single time, but with `1.7.4` it gets called four times.

**Comment by k-paxian** [comment]
Thank you for your patience 👍 
Indeed, that was a deserialization context refactoring side effect. Should be fine now.
