### ISSUE TITLE
Required field on annotation

### ISSUE THREAD

**Issue by agilob** [k-paxian/dart-json-mapper#108]
Any field needs to be annotated with required=true which will return error when field is not present in JSON (my understanding is it **can** be `{field:null}` but has to be in JSON). Required is to make user specifically set field to a value, rather than not include when null.

**Comment by kuhnroyal** [comment]
That is correct, in OAS fields can be `required` (need to be part of the JSON payload) and `nullable` (may be `null`)  at the same time.

**Comment by k-paxian** [comment]
Released as of `1.7.7`

**Comment by kuhnroyal** [comment]
This is only half of it. It also needs to be serialized as `null` as the sever might do the same check.

**Comment by agilob** [comment]
Yes, serialisation and deserialisation needs to be bi-directional in ways:

1. JSON string from serialisation need to be equal to JSON string used in deserialisation
2. correctly written `==` method on pre and post serialisation objects needs to return true

**Comment by k-paxian** [comment]
Makes perfect sense, I'll enhance those checks over serialization as well.
