### ISSUE TITLE
Parameter enumValues is probably ignored

### ISSUE THREAD

**Issue by fidlip** [k-paxian/dart-json-mapper#11]
Given this dummy code fragment:
```
import 'package:dart_json_mapper/json_mapper.dart';

import 'main.reflectable.dart';

enum OperationType { insert, update, remove }

const operationTypeValues = ["__insert", "__update", "__remove"];

@jsonSerializable
class XYZ {
  @JsonProperty(enumValues: operationTypeValues)
  OperationType operation = OperationType.insert;
}


void main() {
  initializeReflectable();


  var xyz = XYZ()..operation = OperationType.update;
  print(JsonMapper.serialize(xyz));

}
```
it will print

> {
>  "operation": "OperationType.update"
> }

So what is wrong? Why is actually enumValues needed?

**Comment by k-paxian** [comment]
Hey @fidlip 
Thanks for mentioning this case.

Actually, enumValues are essential for deserialization, once your snipped is using serialization only it's not an issue. But when and IF you'll need to deserialize it back, you'll be given a runtime error pointing to that fact that you have provided wrong enumValues.

**Comment by fidlip** [comment]
Thank you for clarification.
