### ISSUE TITLE
Support for String/Num Enum values

### ISSUE THREAD

**Issue by agilob** [k-paxian/dart-json-mapper#110]
Enum needs to be annotated what value we see in code and what name of the value is in JSON. eg 
 * `enum Color {Red, Blue}` I need to be able to use `Color.Red` in Dart, but serialise `Red` to `red` In [real life example](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml#L603), `(zyx)` or `_abc` are valid enum values that can be present in JSON
 * Smiliarly for numeric enums `1.1` and `-2` are [valid values](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml#L641) 
Value in code is something we generated in openapi, eg. in spec you see `-1.1` we should generate minusOneDotOne or something similar, but we need a way to tell JSON serialiser to turn `minusOneDotOne` into `-1.1` in JSON and it has to be `-1.1` double value not string value `"-1.1"`

**Comment by agilob** [comment]
This must also be compatible with defaultValue

**Comment by kuhnroyal** [comment]
That is probably not possible with pure enums.

**Comment by agilob** [comment]
It's supported with json_serializable

**Comment by agilob** [comment]
This issue is also the lowest priority of the 3, it's more like "nice to have" than a blocker.

**Comment by k-paxian** [comment]
It has to be properly designed first. It could take some time to nail it down nicely.
* It needs to respect `defaultValue` [here](https://github.com/k-paxian/dart-json-mapper/blob/d9734cef597cac3f6196972e5f808bca2f13c959/mapper/test/test.enums.dart#L129)
* It needs to respect `CaseStyle` [here](https://github.com/k-paxian/dart-json-mapper#name-casing-styles-pascal-kebab-snake-snakeallcaps)
* It needs to respect simultaneously customization via custom converter [here](https://github.com/k-paxian/dart-json-mapper#enum-types) and play nicely with the default global converter.
* It requires to be supported from the builder side with additional annotation (like @JsonValue from `json_serializable`)

**Comment by agilob** [comment]
>It needs to respect CaseStyle here

I agree but that's one caveat, different openapi generators have different options for naming conventions, there is no strict standard about it. All styling and naming conventions are just up to what developers of a generator produce. There are some generators that allow users to produce differently formatted code. This [schema](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml#L603) is pain in the ass for many generators because of the enums. It's really full of edge cases, pain-points, full of unrealistic type structures, types and names. 

In the end it's up to **us** openapi-generator developers what naming convention we use, and it's always, 100%, camelCase, but we also _shouldn't restrict_ anyone from adding another generator with kebab-case or _HaNAnMONtanACas-E_ if they wish so.

>It requires to be supported from the builder side with additional annotation (like @JsonValue from json_serializable)

Yes, that's actually the good thing in json_serializable, but also the bad thing (only used enums have generated builders. Standalone enums that aren't used in any classes do not get the marshaller/unmarshaller code generated. If it only had an annotation for `@JsonEnum` it would be ready for our openapi-generator.

>It needs to respect defaultValue here

The check the schema above, it has enum field with default value line [607](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml#L607)

**Comment by agilob** [comment]
And again, it's a nice-to-have than a must-have. Your library is solving the blocker we had in json_serializer, so it's already better suited I think.

I'm going to try your library in my project over the weekend and try to prepare a PR in openapi-generators if I have enough time.

**Comment by k-paxian** [comment]
Shipped: https://github.com/k-paxian/dart-json-mapper#enums-having-string--num-values

**Comment by agilob** [comment]
Have to say, impressive.
