### ISSUE TITLE
Introduce Firebase adapter

### ISSUE THREAD

**Issue by cedvdb** [k-paxian/dart-json-mapper#119]
At the moment I'm using a converter that is not a `ICustomConverter` from dart_json_mapper prior to turn my firestore data into classes via JsonMapper.

  ```dart
/// helper to convert a document snapshot to a map like a map we'd receive
  /// after json decoding a normal API
  Map<String, dynamic> docToMap(DocumentSnapshot doc) {
    Map<String, dynamic> map = Map();
    final data = doc.data();

    if (data == null) return null;

    map['id'] = doc.id;
    data.entries.forEach((entry) {
      var value = entry.value;
      // if the value is a google timestamp we convert it to a datetime
      if (value is Timestamp) {
        value = value.toDate();
      }
      map[entry.key] = value;
    });
    return map;
  }
```

I had a look at ICustomConverter but apparently it's expecting json, I'm wondering if there is a feature I can use to make this into a dart_json_mapper converter

**Comment by k-paxian** [comment]
What's the goal? I think the most appropriate will be to introduce a brand new `firebase` adapter capable to cope with all fireTypes `DocumentSnapshot, Timestamp` etc.
