### ISSUE TITLE
Support for subclass using a discriminator property

### ISSUE THREAD

**Issue by Kayes-Islam** [k-paxian/dart-json-mapper#120]
I have the following classes:
```dart
@jsonSerializable
abstract class GroupItem {
  GroupItemType get itemType;
}

@jsonSerializable
class GroupItemPerson extends GroupItem {
  @override
  GroupItemType get itemType => GroupItemType.person;

  String name;
}

@jsonSerializable
class GroupItemSection extends GroupItem {
  @override
  GroupItemType get itemType => GroupItemType.section;

  String title;
}

@jsonSerializable
enum GroupItemType { person, section }
```

`itemType` enum is the discriminator property here. Is there any way to use the discriminator property here rather than using the `@Json(typeNameProperty: 'typeName')`?

**Comment by k-paxian** [comment]
Not just jet, but it's totally possible as a new feature.

**Comment by Kayes-Islam** [comment]
@k-paxian Yes that is the requirement. The reason is that the `itemType` enum values is stored in the database and is part of the class, hence it would be nice to be able to use it. 

Similar concept of mapping is implemented in the NHibernate library for example, in table per subclass mapping strategy. The way they do it is they mark a discriminator property on the super class, then add the discriminator value on the child class. So mapping their approach here it would look like something like this:

```
@jsonSerializable
@Json(
  discriminator: 'itemType'
)
abstract class GroupItem {
  GroupItemType get itemType;
}

@jsonSerializable
@Json(
  discriminatorValue: GroupItemType.person
)
class GroupItemPerson extends GroupItem {
  @override
  GroupItemType get itemType => GroupItemType.person;

  String name;
}

@jsonSerializable
@Json(
  discriminatorValue: GroupItemType.section
)
class GroupItemSection extends GroupItem {
  @override
  GroupItemType get itemType => GroupItemType.section;

  String title;
}

@jsonSerializable
enum GroupItemType { person, section }
```
The benefit of this approach is that it's then more SOLID - Open for extension. 

However, in terms of implementation if this is too much effort, I think Option 2 is a good solution out of the three you suggested. Not being able to define it globally would be better because the meaning of the value could translate to different subclass in a different hierarchy, which I think is better to restrict the developer to declare on per class hierarchy.

**Comment by k-paxian** [comment]
Cool 😎 l like it. Thank you so much for taking your time outlining the idea.

**Comment by Kayes-Islam** [comment]
Thank you for the effort in the amazing library :)

**Comment by k-paxian** [comment]
Since `2.0.5`, it is possible to define your case like

```dart
@jsonSerializable
enum GroupItemType { person, section }

@jsonSerializable
@Json(discriminatorProperty: 'itemType')
abstract class GroupItem {
  GroupItemType? itemType;
}

@jsonSerializable
@Json(discriminatorValue: GroupItemType.person)
class GroupItemPerson extends GroupItem {
  String name;
}

@jsonSerializable
@Json(discriminatorValue: GroupItemType.section)
class GroupItemSection extends GroupItem {
  String title;
}
```

Please check if this will be sufficient

**Comment by Kayes-Islam** [comment]
Thanks @k-paxian. Sorry I was a bit late to test this.

I am getting an error on deserialize:

> ReflectableNoSuchMethodError (NoSuchCapabilityError: no capability to invoke the constructor ""
> Receiver: GroupItem
> Arguments: []
> Named arguments: {}
> )

Here's what my code looks like:

```
import 'package:dart_json_mapper/dart_json_mapper.dart'
    show Json, JsonMapper, jsonSerializable;

import 'main.mapper.g.dart' show initializeJsonMapper;

@jsonSerializable
class SequenceGroup {
  String name;
  List<GroupItem> items = [];
}

@jsonSerializable
@Json(discriminatorProperty: 'itemType')
abstract class GroupItem {
  GroupItemType get itemType;
}

@jsonSerializable
@Json(discriminatorValue: GroupItemType.person)
class GroupItemPerson extends GroupItem {
  @override
  GroupItemType get itemType => GroupItemType.person;

  String name;
}

@jsonSerializable
@Json(discriminatorValue: GroupItemType.section)
class GroupItemSection extends GroupItem {
  @override
  GroupItemType get itemType => GroupItemType.section;

  String title;
}

@jsonSerializable
enum GroupItemType { person, section }

main() {
  initializeJsonMapper();

  var obj = new SequenceGroup()
    ..name = 'test group'
    ..items = [
      GroupItemPerson()..name='pose 1',
      GroupItemSection()..title='section 1'
    ];

  var json = JsonMapper.serialize(obj);
  print(json);

  var convertedBack = JsonMapper.deserialize<SequenceGroup>(json);
  print(JsonMapper.serialize(convertedBack));
}

```
I'm getting the exception thrown on line 52 `var convertedBack = JsonMapper.deserialize<SequenceGroup>(json);`.

**Comment by Kayes-Islam** [comment]
@k-paxian when I change my discriminator property from a getter to a readonly field, it's now working. So the below works. 

```
@jsonSerializable
@Json(discriminatorProperty: 'itemType')
abstract class GroupItem {
  GroupItem(this.itemType);
  final GroupItemType itemType;
}

@jsonSerializable
@Json(discriminatorValue: GroupItemType.person)
class GroupItemPerson extends GroupItem {
  GroupItemPerson(): super(GroupItemType.person){
  }

  String name;
}

@jsonSerializable
@Json(discriminatorValue: GroupItemType.section)
class GroupItemSection extends GroupItem {

  GroupItemSection(): super(GroupItemType.section){
  }

  String title;
}
```
The difference is that itemType is a read-only field rather than an abstract getter. Thank you for resolving the issue.

**Comment by k-paxian** [comment]
ok, I'll add extra check for the getter-only case. Thanks for testing it out.
