### ISSUE TITLE
Support deserialization from type variable

### ISSUE THREAD

**Issue by schultek** [k-paxian/dart-json-mapper#121]
Currently the options to define the resulting type for deserialization are either
1) provide a generic type attribute: `JsonMapper.deserialize<MyClass>(data);`
2) provide a template instance: `JsonMapper.deserialize(data, DeserializationOptions(template: MyClass()))`

It would be great if we could have a third way, by providing a type variable to the `deserialize` method, possibly also by using the `DeserializationOptions` like this:

`JsonMapper.deserialize(data, DeserializationOptions(type: someTypeVariable))`

This would allow for more use cases, where we neither have an instance of the target type, nor a type attribute. In my case I have my own reflection-based library, for which I want to use dart-json-mapper for serialization, but I can only get type variables from the reflectors to pass to the deserialization method.

Implementation-wise, this should be pretty straightforward, since we could directly use the type variable whenever no type argument and template is present.

**Comment by k-paxian** [comment]
Actually there is one more you've missed. Type inferred from destination variable.

'''dart
var Type instance = JsonMapper().deserialize(json)
'''

**Comment by schultek** [comment]
Yes, but it has the same effect as 1) since the type argument is inferred from the type declaration, which doesn't exist in this use-case. Or am I missing something?

**Comment by k-paxian** [comment]
Sure, the final effect is the same, but the code snippets are different.

```dart
var Type instance = JsonMapper.deserialize(json)
```
Equals to

```dart
final instance = JsonMapper.deserialize<Type>(json)
```
