### ISSUE TITLE
Can't use fromMap with DateTime

### ISSUE THREAD

**Issue by cedvdb** [k-paxian/dart-json-mapper#126]
```
      map['createdAt'] = DateTime.now();
      final value = JsonMapper.fromMap<T>(map);
```

│ ⛔ Converting object to an encodable object failed: Instance of 'DateTime'

The property createdAt is also a DateTime on the target object. considering there is nothing to change I'd assume this should work

**Comment by k-paxian** [comment]
Thank you so much for reporting it, that was a much broader issue, not just `DateTime` related, it was only a trigger for it
