### ISSUE TITLE
ignoreForSerialization not working properly

### ISSUE THREAD

**Issue by cedvdb** [k-paxian/dart-json-mapper#136]
I think ignoreForSerialization is not working properly or is mixed up with ignoreForDeserialization.

I have a class like this:

```dart
@jsonSerializable
class Metadata {
  @JsonProperty(ignoreForSerialization: true)
  final String id;
  // ...
```

when deserializing (from a map to the object) that contains the id property I get an error:

```
E/flutter (19252): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: type 'Null' is not a subtype of type 'String'
E/flutter (19252): #0      _data.<anonymous closure>.<anonymous closure>
package:sent/main.mapper.g.dart:38
E/flutter (19252): #1      Function._apply (dart:core-patch/function_patch.dart:11:30)
E/flutter (19252): #2      Function.apply (dart:core-patch/function_patch.dart:34:12)
E/flutter (19252): #3      ClassMirrorBase.newInstance
package:reflectable/src/reflectable_builder_based.dart:669
E/flutter (19252): #4      JsonMapper._deserializeObject
package:dart_json_mapper/src/mapper.dart:903
```

I don't get that error if I use ignoreForDeserialization instead, which doesn't make sens, if anything, that one should throw an error.

are ignoreForSerialization and ignoreForDeserialization mixed up ?

**Comment by k-paxian** [comment]
> ... that contains the id property ...

Can you share more details on your map/json you are trying to deserialize, my guess is that your Map indeed contains 'id' key, but the value is `null` and this value cannot be set into non-nullable string field

**Comment by cedvdb** [comment]
the value is not null.

Also it works for deserialisation which and it should be the opposite.

I didn't test it in a sandboxed environment but my classes are as such:


```


@jsonSerializable
class Preferences implements Entity {
  final String defaultCountryIsoCode;

  /// can be null if user didn't specify his will yet
  final bool? autoImportContacts;
  final Metadata metadata;

  Preferences({
    required this.metadata,
    required this.defaultCountryIsoCode,
    required this.autoImportContacts,
  });

  @override
  String toString() =>
      'Preferences(countryIsoCode: $defaultCountryIsoCode, autoImportContacts: $autoImportContacts, metadata: $metadata)';
}


@jsonSerializable
class Metadata {
  @JsonProperty(ignoreForDeserialization: true)
  final String id;
  final String createdBy;
  final DateTime updatedAt;
  final DateTime createdAt;
  @JsonProperty(defaultValue: false)
  final bool deleted;

  Metadata({
    required this.id,
    required this.createdBy,
    this.deleted = false,
  });

  @override
  String toString() {
    return 'Metadata(id: $id, createdBy: $createdBy)';
  }
}
```

data:

```
{
  "defaultCountryIsoCode": "US"
    "metadata": {
      "createdBy": "e5PPxnqulIgBslobDZPXVweoTCC2"
      "id": "e5PPxnqulIgBslobDZPXVweoTCC2"
    }
}
```

**Comment by k-paxian** [comment]
I've checked your code, even put up a [unit test ](https://github.com/k-paxian/dart-json-mapper/blob/master/mapper/test/test.required.dart) and it's 🟢 

My other guess is that your code is desynchronized with the generated code, please make sure to run:
> pub run build_runner build --delete-conflicting-outputs

and verify it in runtime after fresh generated code.

**Comment by cedvdb** [comment]
It is actually the fromMap method that I'm using for deserialization, it indeed works when using deserialize like this instead of fromMap (where data is a map):

```
    final converted = JsonMapper.deserialize<T>(jsonEncode(data))!;
```

**Comment by cedvdb** [comment]
Hmm maybe I spoke too fast, I need to dig some more tomorrow..
