### ISSUE TITLE
Type Exception when using templates for serialization.

### ISSUE THREAD

**Issue by moneer-muntazah** [k-paxian/dart-json-mapper#139]
Hi k-paxian,

```dart
@jsonSerializable
class CheckoutOrderSummary {
    CheckoutOrderSummary({
    required this.base_grand_total,
    required this.discount_amount,
    required this.tax_amount,
    required this.subtotal_incl_tax,
  });
  final double base_grand_total;
  final double discount_amount;
  final double tax_amount;
  final double subtotal_incl_tax;
}
void main(List<String> arguments) {
  initializeJsonMapper();
  final json = '''
   {
      "base_grand_total":650.4,
      "discount_amount":0.0,
      "tax_amount":84.88,
      "subtotal_incl_tax":635.4
   }
  ''';
  final address = JsonMapper.fromJson<CheckoutOrderSummary>(json);

  print(JsonMapper.toJson(address, SerializationOptions(template: {'one': '1'})));
}
```

The example will throw exception. You will get different error messages depending on the content of the JSON and the template.

Thank you

**Comment by k-paxian** [comment]
Well, from your snippet appears that it's type coercion problem.
* Template is treated as type ` Map<String, String>` by default, and you are trying to put a `double` value into a `String` type
* For your case would be appropriate to specify precise type for a template object `<String, dynamic>{'one': '1'}` 

Let me know if you have any other variations of this behavior.

**Comment by moneer-muntazah** [comment]
That makes sense. Thank you
