### ISSUE TITLE
Any tips on how to use it with multiple model files ?

### ISSUE THREAD

**Issue by diegomgarcia** [k-paxian/dart-json-mapper#14]
Hi guys, 

It seems to have a bug when trying to use it with the follow structure: 

- lib
   - models
     - model1.dart
     - model2.dart

I've looked at the generated model1.reflectable.dart and model2.reflectable.dart and the initializeReflectable changes the r.data to the new one so I think this is causing the miss behavior.

Any tips on that ? I didnt dig deep to see how the internals are working.

**Comment by k-paxian** [comment]
Hey @diegomgarcia 
Please describe your case in more details, with code examples. What is miss behavior?

**Comment by diegomgarcia** [comment]
I think its something related to the ServiceOrderModel customer child, because if I comment the constructor of my ServiceOrderApiProvider the customers work fine, but when fetching the orders I get that error that I've posted before.

```
ServiceOrderApiProvider(){
    ServiceOrderModel.setupReflection();
    ServiceOrderItemModel.setupReflection();
  }

```

**Comment by k-paxian** [comment]
- First of all, I guess you should invoke initializeReflectable() only once as a part of your main program entry point. No real need to replicate this call as a part of each model class file.

- Straight out of the error, it seems you are trying to instantiate CustomerModel using only one argument ID, but it is required to provide two arguments id + name.  Probably your service is giving you the json with the id field only, w/o name field?

**Comment by diegomgarcia** [comment]
Indeed the initializeReflectable() was the one that was causing that error, I've commented out and leave just one to see it and it pass it. 
But now I'm getting the follow:

[VERBOSE-2:shell.cc(184)] Dart Error: Unhandled exception:
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<dynamic>'
#0      JsonMapper.deserializeObject (package:dart_json_mapper/json_mapper.dart:511:21)
#1      JsonMapper.deserializeObject.<anonymous closure> (package:dart_json_mapper/json_mapper.dart:514:26)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#3      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#4      JsonMapper.deserializeObject (package:dart_json_mapper/json_mapper.dart:515:12)
#5      JsonMapper.deserialize (package:dart_json_mapper/json_mapper.dart:54:21)
#6      ServiceOrderApiProvider.fetchOpenedServiceOrder (package:itcheckin/src/resources/serviceorder_api_provider.dart:61:51)
<asynchronous suspension>
#7      Repository.fetchOpenedServiceOrder (package:itcheckin/src/resources/repository.dart:25:96)
#8      ServiceOrderBloc.fetchOpenedServiceOrder (package:itcheckin/src/blocs/serviceorder_bloc.dart:29:56)

**Comment by k-paxian** [comment]
@diegomgarcia 

response.body is not as of List type, it is actually Map<String, dynamic>
so you'd better use   List<CustomerModel> customers = JsonMapper.fromMap(response.body);

**Comment by diegomgarcia** [comment]
Strange the body seems to be a string, I've tried that before ... 

Changing to it I get the follow: 

[VERBOSE-2:shell.cc(184)] Dart Error: Unhandled exception:
'package:itcheckin/src/resources/serviceorder_api_provider.dart': error: line 62 pos 49: lib/src/resources/serviceorder_api_provider.dart:62:49: Error: The argument type 'dart.core::String' can't be assigned to the parameter type 'dart.core::Map<dart.core::String, dynamic>'.
Try changing the type of the parameter, or casting the argument to 'dart.core::Map<dart.core::String, dynamic>'.
      List orders = JsonMapper.fromMap(response.body);
                                                ^

**Comment by k-paxian** [comment]
Ok, could you share that response.body string then?

**Comment by diegomgarcia** [comment]
Yeap sure

```
[
  {
    "Id": 96,
    "Number": 96,
    "CustomerId": 1,
    "Customer": {
      "Id": 1,
      "Name": "Hyspex",
      "Emails": [
        {
          "Id": 1,
          "Name": "Arthur",
          "Address": "arthur@hyspex.com.br"
        },
        {
          "Id": 2,
          "Name": "Fernanda",
          "Address": "fernanda@hyspex.com.br"
        }
      ]
    },
    "ExpertId": 1,
    "Expert": {
      "Name": "Diego Garcia",
      "Title": "Diretor Técnico"
    },
    "Start": "2019-02-12T15:06:21.313144",
    "End": null,
    "Resume": null,
    "Items": []
  }
]
```

**Comment by k-paxian** [comment]
- CustomerModel requires id + name in constructor, json has "id" property only, no "name" at root level.
- If you have unbalanced json/class, it would be better to use named arguments instead of positional arguments in CustomerModel({this.id, this.name}) and add class fields one by one.

**Comment by diegomgarcia** [comment]
I don't think thats the reason, as this json root maps to ServiceOrder and not Customer, it has a child that is the CustomerModel, if you look at the CustomerModel class the constructor has the id and name on it.

**Comment by k-paxian** [comment]
sorry, misunderstood classes hierarchy.
Then you definitely need more decorators, one per each custom list type
```dart
      JsonMapper.registerValueDecorator<List<ServiceOrderModel>>((value) => value.cast<ServiceOrderModel>());
      JsonMapper.registerValueDecorator<List<ServiceOrderItemModel>>((value) => value.cast<ServiceOrderItemModel>());
```

**Comment by diegomgarcia** [comment]
Yeap I've already setup that decorators ... 

I've refactored the code and ported all decorators to this class: 

```
class ModelInitializer {
  static Initialize(){
    initializeReflectable();

    CustomerModel.setupReflection();
    EmailModel.setupReflection();
    ServiceOrderModel.setupReflection();
    ServiceOrderItemModel.setupReflection();
  }
}
```

And now I just call it on the first line of the main(). 

The setupReflection just register the decorator for each class.


But the error still the same: 

[VERBOSE-2:shell.cc(184)] Dart Error: Unhandled exception:
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<dynamic>'
#0      JsonMapper.deserializeObject (package:dart_json_mapper/json_mapper.dart:511:21)
#1      JsonMapper.deserializeObject.<anonymous closure> (package:dart_json_mapper/json_mapper.dart:514:26)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#3      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#4      JsonMapper.deserializeObject (package:dart_json_mapper/json_mapper.dart:515:12)
#5      JsonMapper.deserialize (package:dart_json_mapper/json_mapper.dart:54:21)
#6      ServiceOrderApiProvider.fetchOpenedServiceOrder (package:itcheckin/src/resources/serviceorder_api_provider.dart:57:51)
<asynchronous suspension>
#7      Repository.fetchOpenedServiceOrder (package:itcheckin/src/resources/repository.dart:25:96)
#8      ServiceOrderBloc.fetchOpenedServiceOrder (package:itcheckin/src/blocs/serviceorder_bloc.dart:29:56)

**Comment by k-paxian** [comment]
@diegomgarcia 
I've added working test with your case, please consult the commit changes.
I assume you are calling it like that:
      List orders = JsonMapper.deserialize(response.data);
But it should be precise type inferred:
      List<ServiceOrderModel> orders = JsonMapper.deserialize(response.data);

**Comment by diegomgarcia** [comment]
should i run package update?

**Comment by k-paxian** [comment]
No, it's just FYI, unit test only, no changes in the library.

**Comment by diegomgarcia** [comment]
Ah ok, the strange thing is that I've change to type infered but it keeps trowing the same error :/

![image](https://user-images.githubusercontent.com/1318829/54478471-4ad9f800-47f1-11e9-9f8c-e6b809bfb3d1.png)

[VERBOSE-2:shell.cc(184)] Dart Error: Unhandled exception:
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<dynamic>'
#0      JsonMapper.deserializeObject (package:dart_json_mapper/json_mapper.dart:511:21)
#1      JsonMapper.deserializeObject.<anonymous closure> (package:dart_json_mapper/json_mapper.dart:514:26)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#3      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#4      JsonMapper.deserializeObject (package:dart_json_mapper/json_mapper.dart:515:12)
#5      JsonMapper.deserialize (package:dart_json_mapper/json_mapper.dart:54:21)
#6      ServiceOrderApiProvider.fetchOpenedServiceOrder (package:itcheckin/src/resources/serviceorder_api_provider.dart:57:51)
<asynchronous suspension>
#7      Repository.fetchOpenedServiceOrder (package:itcheckin/src/resources/repository.dart:25:96)
#8      ServiceOrderBloc.fetchOpenedServiceOrder (package:itcheckin/src/blocs/serviceorder_bloc.dart:29:56)
<a<…>

**Comment by k-paxian** [comment]
Well, the best I could suggest is to compare code from unit test 
[https://github.com/k-paxian/dart-json-mapper/commit/b434fea77b00c3558cfe9d32002dfb06e775d78c](https://github.com/k-paxian/dart-json-mapper/commit/b434fea77b00c3558cfe9d32002dfb06e775d78c)
with your code.

**Comment by diegomgarcia** [comment]
Yeap that is what I'm doing... I will try to do a flutter upgrade, maybe is something related to my version.

**Comment by diegomgarcia** [comment]
I thinks its something related to my files separation ... I will try to put it all together on the same files. 

I've tried to convert to part but when doing this the pub run didnt generate the reflection file ...

Just for test I will put it all together.

**Comment by diegomgarcia** [comment]
Indeed the problem was with the file separation as I've was thinking at first ... 

if you use as a part of it works just fine because it generates only one reflactable.dart files but if you separate it generates several reflactable one for each file and this causes the problem as if you call initializeReflectable on each one they loses the previous ... I think the best way to solve this would it be to change the generated reflectable.dart to something like that:

```
initializeReflectable() {
  r.data.add(_data);
  r.memberSymbolMap.add(_memberSymbolMap);
}

```

So with that it wouldnt loses the previous.

**Comment by k-paxian** [comment]
@diegomgarcia 
Aha, I see, nice that you've discovered that. Unfortunately this aspect is not under my control, it's [reflectable ](https://pub.dartlang.org/packages/reflectable) library from google.

And where is my star? ;)

**Comment by diegomgarcia** [comment]
Haha its there ;) 

Thanks @k-paxian for the help on investigate this issue :)
