### ISSUE TITLE
Referencing to owning parent object

### ISSUE THREAD

**Issue by Atokulus** [k-paxian/dart-json-mapper#144]
Dear Alexander, dear community

This is @atokulus from Zurich. I had a look at your library `dart-json-mapper` and it looks very promising 😁👍

I intend to use it for storing `MobX.dart` stores to `shared_preferences`.

One of the big challenges that come into play (as probably with many de-/serialization libraries) is my objects referencing their owning parent (ownership, not inheritance) similar to following structure:

```dart

class Child {
  Child(this.parent);

  final Parent parent;
}

class Parent {
  List<Child> children = [];
}
```

Checking your documentation and sources, there does not seem support for this within the `@jsonConstructor` annotation.
I would propose to support something as the following:

```dart

@jsonSerializable
class Child {
  Child(this.parent);

  @jsonConstructor
  Child.fromJson(@JsonParent Parent parent)
      : this.parent = parent;

  @JsonProperty(ignore: true)
  final Parent parent;
}
```

Do you believe this would make sense to you? Or is a solution similar to https://github.com/k-paxian/dart-json-mapper#relative-path-reference-to-parent-field-from-nested-object-id better?

As I would like to address this for my project, a pull request might soon follow.

Have a nice day 😉
Markus

**Comment by k-paxian** [comment]
I'm not sure I've got the challenge right.

Could you please provide an example of desired  JSON output alongside dart code snippet. Really basic one just illustrating the case.

What intention is behind your new annotation @JsonParent? If you'll omit it it should work as expected no?

**Comment by Atokulus** [comment]
Dear @k-paxian
Wow, this was fast 😊
I totally agree with you and it would make sense indeed:

```dart
@jsonSerializable
class Child {
  Child(this.parent);

  @jsonConstructor
  Child.fromJson(@JsonProperty(name: '..') Parent parent)
      : this.parent = parent;

  @JsonProperty(ignore: true)
  final Parent parent;
}
```

I'll try to implement it on my fork and hope to have soon some merge request ready.

Best regards
Markus

**Comment by k-paxian** [comment]
Yep, and here should be
@JsonProperty(ignoreForSerialization: true)

Because having general ignore: true will omit setting parent property.

**Comment by Atokulus** [comment]
```dart
  @JsonProperty(ignoreForSerialization: true)
```

Just realized this when debugging my code (spent quite some time 😂)

Code is running now and merge request will follow shortly.

Best regards
Markus

**Comment by k-paxian** [comment]
@Atokulus Thank you for proactive contribution ❤️ , anyway for some reason github is not listing you as a contributor 🤷 
The feature is published, feel free to provide more feedback 🤞
