### ISSUE TITLE
[ version conflict ] can't install latest version 2.1.3

### ISSUE THREAD

**Issue by AlaaEldeenYsr** [k-paxian/dart-json-mapper#145]
```
[project] flutter pub get
Running "flutter pub get" in project...                         
Because dart_json_mapper >=2.1.3 depends on meta ^1.4.0 and every version of flutter from sdk depends on meta 1.3.0, dart_json_mapper >=2.1.3 is incompatible with flutter from sdk.
```
latest version 2.1.3 of ```dart_json_mapper``` has a conflict with flutter sdk 2.2.3

**Comment by k-paxian** [comment]
Please consider waiting for the new stable version of flutter sdk to upgrade.
https://github.com/flutter/flutter/blob/master/packages/flutter/pubspec.yaml depends even on meta package ^1.7.0
