### ISSUE TITLE
Nullable list throws exception on being serialized when null

### ISSUE THREAD

**Issue by Atokulus** [k-paxian/dart-json-mapper#152]
Dear community, dear @k-paxian

Working a bit more with `dart-json-mapper` I encountered an issue when serializing nullable types.

In particular, a **nullable list throws an exception on being serialized when being null**.

### Cause

Assume you have a structure as the following:

```dart
@jsonSerializable
class MyExample {
  List<int>? myList = null;
}
```

On serialization the converter at https://github.com/k-paxian/dart-json-mapper/blob/master/mapper/lib/src/model/converters.dart#L461 will call `.toList` on `null`, throwing an exception.

### Expected behaviour
The object should be serialized as `null` or not be serialized at all.

### Mitigation

I suggest to add a null check to https://github.com/k-paxian/dart-json-mapper/blob/master/mapper/lib/src/model/converters.dart#L461

```dart
/// Default Iterable converter
class DefaultIterableConverter implements ICustomConverter, ICustomIterableConverter, IRecursiveConverter {

  // ...

  @override
  dynamic toJSON(dynamic object, [SerializationContext? context]) {
    if (object != null) {
      return object.map((item) => _serializeObject(item)).toList();
    } else {
      return null;
    }
  }
```

I'd be very glad if you could the issue yourself 😀

Best regards and have a nice day
Markus

**Comment by k-paxian** [comment]
Dear @Atokulus ,

Thank you for reporting this shameful issue 😊 
I'm grateful for your help in doing it better step by step.

Should be ok now with the release `2.1.6`

**Comment by Atokulus** [comment]
Wow 😄 This was fast. Thank you patching this.

Best regards
Markus

**Comment by au-top** [comment]
Hello, I have the same problem

I have two projects. In one of them, he will automatically set

```dart
inal mainGeneratedAdapter = JsonMapperAdapter(
  title: 'free_store',
  url: 'package:free_store/main.dart',
  reflectableData: _data,
  memberSymbolMap: _memberSymbolMap,
  valueDecorators: {
    typeOf<List<x0.BasePackage>>(): (value) => value.cast<x0.BasePackage>(),
    typeOf<Set<x0.BasePackage>>(): (value) => value.cast<x0.BasePackage>(),
    typeOf<List<x0.SignUpPackage>>(): (value) => value.cast<x0.SignUpPackage>(),
    typeOf<Set<x0.SignUpPackage>>(): (value) => value.cast<x0.SignUpPackage>(),
    typeOf<List<x0.SignInPackage>>(): (value) => value.cast<x0.SignInPackage>(),
    typeOf<Set<x0.SignInPackage>>(): (value) => value.cast<x0.SignInPackage>(),
    typeOf<List<x0.AppIndexInfo>>(): (value) => value.cast<x0.AppIndexInfo>(),
    typeOf<Set<x0.AppIndexInfo>>(): (value) => value.cast<x0.AppIndexInfo>(),
    typeOf<List<x0.RegisterAppPackage>>(): (value) => value.cast<x0.RegisterAppPackage>(),
    typeOf<Set<x0.RegisterAppPackage>>(): (value) => value.cast<x0.RegisterAppPackage>(),
    typeOf<List<x0.AppOtherLink>>(): (value) => value.cast<x0.AppOtherLink>(),
    typeOf<Set<x0.AppOtherLink>>(): (value) => value.cast<x0.AppOtherLink>(),
    typeOf<List<x0.AppVersionLog>>(): (value) => value.cast<x0.AppVersionLog>(),
    typeOf<Set<x0.AppVersionLog>>(): (value) => value.cast<x0.AppVersionLog>()
},
  enumValues: {

});
```

But I moved some of the same things to another project

```


final mainGeneratedAdapter = JsonMapperAdapter(
  title: 'free_message',
  url: 'package:free_message/main.dart',
  reflectableData: _data,
  memberSymbolMap: _memberSymbolMap,
  valueDecorators: {

},
  enumValues: {

});

```

Why 
[Bmain.mapper.g.dart.txt](https://github.com/k-paxian/dart-json-mapper/files/8889206/Bmain.mapper.g.dart.txt)
[Amain.mapper.g.dart.txt](https://github.com/k-paxian/dart-json-mapper/files/8889211/Amain.mapper.g.dart.txt)
?
