### ISSUE TITLE
Json deserialization in compute 

### ISSUE THREAD

**Issue by rmasarovic** [k-paxian/dart-json-mapper#153]
Hi i try to use mapper in static method and compute because deserialization freeze thread and made visual glitch. i have this error when i try to run in isolate. Any idea or hint?

[ERROR] Exception: Bad state: Reflectable has not been initialized.
I/flutter ( 5023): Please make sure that the first action taken by your program
I/flutter ( 5023): in `main` is to call `initializeReflectable()`. 

Here is code: 

```
fetch() async{
....
 String json= "big json";
 final Response? responseData = await compute(deserialization, json);
...
}

static Response? deserialization(String json) {
    Response? response = JsonMapper.deserialize<Response>(json);
    return response;
}

```

**Comment by k-paxian** [comment]
Please take a look [here](https://github.com/k-paxian/dart-json-mapper/issues/141) for an example
