### ISSUE TITLE
support config ignoreNullMembers in build.yaml?

### ISSUE THREAD

**Issue by peterweb2005** [k-paxian/dart-json-mapper#154]
thanks

want to use with "ignoreNullMembers",
but how to use it simply?

such as:
config in build.yaml as "dart json serializable"?

thanks

**Comment by k-paxian** [comment]
At the moment you can set this preference on two levels: 
* Class level:

```dart
@jsonSerializable
@Json(ignoreNullMembers: true)
class Bean {
}
```

* DeserializationOptions / SerializationOptions:

```dart
@jsonSerializable
class Bean {
}

final target = JsonMapper.deserialize<Bean>(json, DeserializationOptions(ignoreNullMembers: true))
final targetJson = JsonMapper.serialize(target, SerializationOptions(ignoreNullMembers: true))
```

**Comment by peterweb2005** [comment]
thanks, i knew
i had search the issue
