### ISSUE TITLE
Multi project setup, how to?

### ISSUE THREAD

**Issue by kuromukira** [k-paxian/dart-json-mapper#155]
Hi,

I keep getting this error when I add this package as a dependency
```
Because every version of flutter_test from sdk depends on meta 1.3.0 and dart_json_mapper >=2.1.5 depends on meta ^1.7.0, flutter_test from sdk is incompatible with dart_json_mapper >=2.1.5.
```

I'm adding it to a flutter package that 2 of my apps use (eg `app_core`). Any suggestions?

**Comment by kuromukira** [comment]
I managed to import this to my package by not specifying the version to `dart_json_mapper`.
However, no `mapper.g.dart` file was ever generated. Should there be any other configurations needed for this to be used as a dependency for a package?

**Comment by k-paxian** [comment]
I guess you've missed the step with `build.yaml` from [basic setup](https://github.com/k-paxian/dart-json-mapper#basic-setup) section

**Comment by kuromukira** [comment]
Thanks for the info. I will try the options you mentioned.

**Comment by kuromukira** [comment]
Hi @k-paxian 

Any suggestions for this?
```
Because every version of flutter_test from sdk depends on meta 1.3.0 and dart_json_mapper >=2.1.5 depends on meta ^1.7.0, flutter_test from sdk is incompatible with dart_json_mapper >=2.1.5
```

**Comment by k-paxian** [comment]
The only reasonable suggestion is to wait till `flutter_test` will bump it's dependency

**Comment by k-paxian** [comment]
Here is a more reliable solution since version `2.1.9`, [this ](https://github.com/k-paxian/dart-json-mapper/tree/master/perf-test) project could be used as an example consuming two [shared models](https://github.com/k-paxian/dart-json-mapper/tree/master/models) simultaneously

**Comment by kuromukira** [comment]
Thanks @k-paxian
