### ISSUE TITLE
Referencing relative parent '..' on deserialization from grand-child will reference its grandfather object

### ISSUE THREAD

**Issue by Atokulus** [k-paxian/dart-json-mapper#159]
Dear @k-paxian

I hope you are doing fine 😃

Regarding the feature [Relative path reference to parent itself from nested object ".."](https://github.com/k-paxian/dart-json-mapper#relative-path-reference-to-parent-itself-from-nested-object-) I encountered a problem where a grand-child object will reference its grandparent (rather than its direct parent) on construction, resulting in an exception. E.g. the following code will not work:

```dart
@jsonSerializable
class GrandParent {
  Parent child;
}

@jsonSerializable
class Parent {
  Parent(this.parent);

  // Working as expected
  @JsonProperty(name: '..')
  GrandParent parent;
}

@jsonSerializable
class Child {
  Child(this.parent);

  // Will deserialize to [GrandParent] (but should be the direct [Parent], which results in 
  // Unhandled Exception: type 'GrandParent' is not a subtype of type 'Parent'
  @JsonProperty(name: '..')
  Parent parent; 
}
```

I will try to hand in a fix tomorrow ASAP, but maybe you already might have some suspicions regarding the culprit.

Best regards & have nice evening
Markus

**Comment by k-paxian** [comment]
@Atokulus Thank you for vanishing that 👍 , should be ok now, please let me know if it helps

**Comment by Atokulus** [comment]
Dear @k-paxian 

This was a blazing fast fix again 😮

I checked the solution and encountered some last minor bugs for my own project.

Please see #160 for some bug fixes 😊

Best regards
Markus

**Comment by k-paxian** [comment]
Dear @Atokulus 

Can't even express how cool is that, you've done a fantastic job with the fixes ❤️ Huge thank you for such a tremendous contribution and your time on improving things.

**Comment by Atokulus** [comment]
Many thanks @k-paxian for the integration.
Everything is working now flawlessly 😁👍

Wish you a nice evening
Markus
