### ISSUE TITLE
Doesn't seem to work with redux_remote_devtools

### ISSUE THREAD

**Issue by chirastefan** [k-paxian/dart-json-mapper#161]
Coming from this thread: https://github.com/google/json_serializable.dart/issues/537. I need to serialize the private fields without adding getters and setters as mentioned in that thread.
This package seems really easy to use and clean, but it doesn't seem to work with redux_remote_devtools, is this supported? I couldn't find anything related to this. 
Any feedback would be appreciated. Thanks.

**Comment by k-paxian** [comment]
Can you please illustrate the basic example which didn't work for you, so we could get started from it onwards to formalize the desired outcome.

**Comment by chirastefan** [comment]
Hi, thanks for the reply. So I managed to successfully run the build, but the flutter_redux_dev_tools cannot see the state tree. it's "undefined".

**Comment by k-paxian** [comment]
Unfortunately still tells me nothing about the problem. No code samples, no sample repository reproducing the configuration you have, etc.

**Comment by chirastefan** [comment]
I cannot share the code, but I'll try to make a repo with the mentioned issue.
