### ISSUE TITLE
reflectable list<dynamic>' is not a subtype of type list<XX>

### ISSUE THREAD

**Issue by peterweb2005** [k-paxian/dart-json-mapper#162]
i have 1 project (with a library project) with 2 app projects,
which all data files put in the library project

then both app projects can generate the main.mapper.g.dart,
but one has the problem as the title (the other project is good).
comparing the generated file, i found that one big difference is missing the following lines:
```
    typeOf<List<x0.XX>>(): (value) => value.cast<x0.XX>(),
    typeOf<Set<x0.XX>>(): (value) => value.cast<x0.XX>(),
(and more)
```

found one day and no ideas

**Comment by k-paxian** [comment]
Here is an example of how to consume two shared models simultaneously from two different libraries.
https://github.com/k-paxian/dart-json-mapper/blob/master/perf-test/test/unit/_test.dart

**Comment by k-paxian** [comment]
Here are the model libraries
https://github.com/k-paxian/dart-json-mapper/tree/master/models just follow the example.

**Comment by peterweb2005** [comment]
There should be a file with main method to export the data? Thanks

**Comment by k-paxian** [comment]
Yep!

**Comment by peterweb2005** [comment]
thanks, seen the decorator

closed.
