### ISSUE TITLE
`fromMap` and `toMap` inefficiency due to string serialisation/deserialisation

### ISSUE THREAD

**Issue by buzzware** [k-paxian/dart-json-mapper#168]
I'm using Firebase Firestore and model classes marked with `@jsonSerializable`.

I want to read and write my models to and from Firestore. For reading, the firestore sdk returns a `Map<String,dynamic>` that I want to create a model instance from.
To become a Map, there must be deserialization step inside of the firestore sdk.
I'm using `JsonMapper.fromMap`, which adds serialization & deserialization steps internally, and leads to confusing bugs due to serialization failing when you think you're only deserializing.
It also seems like a lot of waste of memory and processing time, which probably becomes significant with a lot of records.
In general, maps are very useful for manipulating unknown data structures, and are often used as a step in-between class instances and json strings (including by de/serialization libraries), so I think good map support is relevant to this library. 

Please consider implementing fromMap<Model> and toMap(model) as generated code that assigns and converts fields, without the json serialization & deserialization.

**Comment by k-paxian** [comment]
Dear Gary,

Thank you so much for pointing that, indeed there was a redundancy and overhead related to enforcing bidirectional consistency.
I've simplified those methods, hope this helps a bit.

On the other hand over-generation of code following this pattern: `... code that assigns and converts fields ...` will lead to a completely different class of issues like [this](https://github.com/google/json_serializable.dart/issues/881), [this](https://github.com/google/json_serializable.dart/issues/946), etc.
