### ISSUE TITLE
@JsonProperty(ignore: true) not working properly

### ISSUE THREAD

**Issue by ramjke** [k-paxian/dart-json-mapper#173]
```dart
import 'dart:io';
import 'package:dart_json_mapper/dart_json_mapper.dart';

@jsonSerializable
class Folder {
  Folder({this.file});

  @JsonProperty(ignore: true)
  final File? file;
}
```
then JsonMapper.serialize(new Folder(file: localFile)) throws:

**Unhandled Exception: It seems your class '_File' has not been annotated with @jsonSerializable**

Expected:
Serialize ignores file field on serialize

**Comment by k-paxian** [comment]
It's not an intended usage of ignore flag. Instead you would like to ignore unknown type, so for that to work please use following example
```dart
JsonMapper.serialize(new Folder(file: localFile), SerializationOptions(ignoreUnknownTypes: true));
```
