### ISSUE TITLE
Broken code sample from documentation: Field '_name' has not been initialized

### ISSUE THREAD

**Issue by BaptisteMagoni** [k-paxian/dart-json-mapper#175]
Hello,

I try to user your library but i have encountered a problem.

I use 2.15.1 sdk version and when i test your simple exemple for deserialize json to object i have this error message 'Field 'field_name' has not been initialized'.

![image](https://user-images.githubusercontent.com/34521668/147374453-2272f33e-b623-40c1-b908-25e1dd920fff.png)

Thank you in advance for your answer.

**Comment by k-paxian** [comment]
Thank you so much for noticing that. That was a stale code sample prior to null safety dart feature support. Documentation updated.

**Comment by BaptisteMagoni** [comment]
Thank you for your reactivity :)
