### ISSUE TITLE
It would be nice to add IgnoreIfNull to class level, i.e. @jsonSerializable(ignoreIfNull: true)

### ISSUE THREAD

**Issue by slavap** [k-paxian/dart-json-mapper#18]
That will make my classes cleaner, because no need to annotate multiple fields with:
@JsonProperty(ignoreIfNull: true)

**Comment by k-paxian** [comment]
Thank you for a great tip!

Unfortunately, I'm not able to extend `@jsonSerializable` meta tag, due to [reflectable](https://pub.dev/packages/reflectable) library limitation.

So, I've used complementary meta tag `@Json(ignoreNullMembers: true)` to configure that.

```dart
@jsonSerializable
@Json(ignoreNullMembers: true)
class IgnoreNullMembersClass {
  String firstName;
  String lastName;
  String middleName;

  IgnoreNullMembersClass({this.firstName, this.middleName, this.lastName});
}

// given
final instance = IgnoreNullMembersClass(firstName: "Bob");
// when
final target = JsonMapper.serialize(instance, '');
// then
expect(target, '{"firstName":"Bob"}');

```

**Comment by slavap** [comment]
@k-paxian Thank you for implementing it so quickly!
