### ISSUE TITLE
The `@JsonProperty.name` support for aliases doesn't work as advertised

### ISSUE THREAD

**Issue by yangxiaoweihn** [k-paxian/dart-json-mapper#181]
```yaml
sdk: ">=2.15.1 <3.0.0"
path: ^1.8.1
dart-json-mapper: 2.2.1+3
```
## **tested result: Jsonproperty annotation only support the primary name and the last aliases, other aliases ignored.**
code:

```dart
/// entity
@jsonSerializable
class Category {
    @JsonProperty(name: ['id', 'id_a', 'id_b', 'id_test'],)
    int id = 0;
    String uuid = '';
}
```

``` dart
/// test
List<String> test = [
                '''{"id": 90, "name": "id"}''',
                '''{"id_a": 91, "name": "id_a"}''',
                '''{"id_test": 92, "name": "id_test"}''',
                '''{"id_b": 93, "name": "id_b"}''',
            ];
for (var element in test) {
    Log.log(">>>>>  ${JsonMapper.deserialize<Category>(element).toString()}");
    Log.log("\n");
}

```

/// compiled reflectable
<img width="575" alt="aaaaa" src="https://user-images.githubusercontent.com/5101387/156706261-3d4022c1-d5e1-4559-91fd-910454c324a0.png">

/// out put 
![image](https://user-images.githubusercontent.com/5101387/156705913-2015f2cb-edbe-4227-9fca-54784641a78c.png)

## so, Jsonproperty annotation  only support the first `id` and the last `id_test`,  `id_a` and `id_b` in the middle are ignored

**Comment by k-paxian** [comment]
Thank you so much, delivered in `2.2.2` 🎉
