### ISSUE TITLE
New annotated classes in a newly added file are not being included in the build

### ISSUE THREAD

**Issue by rbocobo-kodaris** [k-paxian/dart-json-mapper#185]
New annotated classes in a newly added file are not being included in the build. Existing annotated classes are always included in the build when updated. If I declare a new annotated class in an existing file, that class will be included in the build.

Flutter 2.10.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5464c5bac7 (13 days ago) • 2022-04-18 09:55:37 -0700
Engine • revision 57d3bac3dd
Tools • Dart 2.16.2 • DevTools 2.9.2
Build Runner 2.1.10
darr_json_mapper-2.1.17
dart_json_mapper_flutter-2.0.1

**Comment by k-paxian** [comment]
There is only one reason for that, those classes are not used in the compiled code. Unused code is omitted as dead code.
