### ISSUE TITLE
Ability to have “partial” deserialization from JSON 

### ISSUE THREAD

**Issue by slavap** [k-paxian/dart-json-mapper#19]
In many cases input JSON has many fields, which are not needed for particular UI. So I’m declaring class with let’s say 5 fields out of 20 in JSON. Currently I’m getting error on attempt to deserialize from JSON in such situations, so I have to carefully declare all fields in my classes to be fully consistent with input JSON, which is boring and useless in many cases.

**Comment by k-paxian** [comment]
Fixed in 1.2.0. Thanks for sharing your ideas on improvement
