### ISSUE TITLE
type 'Null' is not a subtype of type 'Object' when serializing Null element in List and Set

### ISSUE THREAD

**Issue by marco709394** [k-paxian/dart-json-mapper#190]
https://github.com/k-paxian/dart-json-mapper/blob/1acf9076e200409c76097386e94f615f2d046c0b/mapper/lib/src/model/converters.dart#L10-L11

Currently `SerializeObjectFunction` does not accept Null as object param, which affects _serializeObject of `defaultIterableConverter` when any element is null.

Should be able to workaround by changing the signature to 
```dart
typedef SerializeObjectFunction = dynamic Function(Object? object, SerializationContext context);
 ```
 but I am not sure if it has any side-effect.

**Comment by k-paxian** [comment]
Delivered, thank you for reporting!
