### ISSUE TITLE
version `2.2.5` incompatible with current stable Flutter `3.0.5`

### ISSUE THREAD

**Issue by maks** [k-paxian/dart-json-mapper#193]
Hi, thanks for the great package!
I just wanted to flag that the current `2.2.5` release is incompatible with the current Flutter stable channel release (3.0.5) due to the `path` package dependency:
```
Because every version of flutter_test from sdk depends on path 1.8.1 and dart_json_mapper >=2.2.5 depends on path ^1.8.2, flutter_test from sdk is incompatible with dart_json_mapper >=2.2.5.
So, because XXXXXXX depends on both dart_json_mapper ^2.2.5+2 and flutter_test from sdk, version solving failed.
pub get failed (1; So, because XXXXXXX depends on both dart_json_mapper ^2.2.5+2 and flutter_test from sdk, version solving failed.)
exit code 1
```
This can be worked around with a override in an apps pubspec:
```
dependency_overrides:
  path: 1.8.1
```

I realise that not all users of dart-json-mapper will be Flutter based, but I just wanted to ask if it's possible for future releases to maintain compatibility with Flutter stable and then those that don't be done as [pre-releases](https://dart.dev/tools/pub/publishing#publishing-prereleases) since while ideally they would be [preview releases](https://dart.dev/tools/pub/publishing#publishing-previews), I can see why that's not feasible given that this package is pure Dart one and not a Flutter plugin with a specified `environment` dependency only on the Dart SDK and not on the Flutter SDK.

**Comment by k-paxian** [comment]
No worries, since `2.2.5+3` should be it.
