### ISSUE TITLE
Cannot deserialize to a class with a constructor that takes an enum

### ISSUE THREAD

**Issue by fasterlars** [k-paxian/dart-json-mapper#198]
I have this enum:

```dart
@JsonSerializable()
enum EActionType { None, Installation, Replacement }
```

I Have this class:

```dart
@JsonSerializable()
class TestModel {
  EActionType type = EActionType.None;
}
```

I have this json:

```dart
var json = {
      'type': 'Installation',
}
```

Deserializing this works just fine 👌

But I need a constructor in my class to instantiate the model in my code logic:

```dart
@JsonSerializable()
class TestModel {
  EActionType type = EActionType.None;

  TestModel(EActionType actionType) {
    type = actionType;
  }
}
```

Now the deserializing fails with: `TypeError (type 'Null' is not a subtype of type 'EActionType')`

If I remove the actionType, so the constructor is empty, the deserialization works fine.

Any clues? 🤔

**Comment by k-paxian** [comment]
well, that should be easy one, it's not obvious that constructor parameter `actionType` needs to be mapped to json field `type`, so you should tell it explicitly how to operate:

```dart
@JsonSerializable()
class TestModel {
  EActionType type = EActionType.None;

  TestModel(@JsonProperty(name: 'type') EActionType actionType) {
    type = actionType;
  }
}
```

This should do the trick, if not let me know

**Comment by fasterlars** [comment]
Makes great sense, and it works ofc :)
Thanks alot! 🍺

**Comment by k-paxian** [comment]
Wow, so generous, thank you so much appreciate that. All I can do for you is my pleasure, challenge me whenever you like

**Comment by fasterlars** [comment]
> 

This library is priceless, and your ability to help and sort out issues so fast is incredible!
