### ISSUE TITLE
Integration with mobx

### ISSUE THREAD

**Issue by felipeleon73** [k-paxian/dart-json-mapper#20]
I'm trying to use this excellent library along with dart mobx. Unfortunately I believe that it does not support the self-generated code with mobx_codegen ...
For example the simple following class obviously works perfectly:

```
@jsonSerializable
class TestChain {
  List<String> mailingList = List<String>();
}

main()
{
  initializeReflectable();
  var test = TestChain();
  test.mailingList.add("test12345@test.com");
  test.mailingList.add("test2222@test.com");
  test.mailingList.add("test33333@test.com");
  var a = JsonMapper.serialize(test); 
  print(a);
  var ab= JsonMapper.deserialize<TestChain>(a);
  print(ab);
}
```
If I modify the class so that I can use mobx (even if I don't insert any observable) 

```
@jsonSerializable
class TestChain extends _TestChain with _$TestChain {

}

@jsonSerializable
abstract class _TestChain with Store{
  List<String> mailingList = List<String>();
}
```
I get the following error at runtime
```
Exception has occurred.
_TypeError (type 'List<dynamic>' is not a subtype of type 'List<String>' of 'value')
```

Any suggestions?

**Comment by k-paxian** [comment]
@felipeleon73 Thank you for letting me know about this. 
Don't worry we'll make it happen, as soon as I'll reproduce this.

**Comment by k-paxian** [comment]
@felipeleon73, It has nothing to do with MobX, it was an inheritance issue.

**Comment by felipeleon73** [comment]
Ok. Thanx!
Now it works with Lists ... how can I make mobx ObservableList work?
If I replace the line
`List<String> mailingList = List<String>();`
with the line
`ObservableList<String> mailingList = ObservableList<String>();`
serialization works correctly, but deserialization gives me an error:
```
Exception has occurred.
FormatException (FormatException: Unexpected character (at character 1)
test12345@test.com
^
)
```
I tried to register both a registerValueDecorator and a registerConverter but without success

**Comment by k-paxian** [comment]
Quick answer is a custom converter for everything custom.
I'll try to put up an example for your case during the day

**Comment by k-paxian** [comment]
@felipeleon73 
Ok, here is the code
```dart
import 'dart:convert' show JsonDecoder, JsonEncoder;
import 'package:mobx/mobx.dart';
import 'package:dart_json_mapper/converters.dart';

class ObservableListStringConverter implements ICustomConverter<dynamic> {
  const ObservableListStringConverter() : super();

  static JsonDecoder jsonDecoder = JsonDecoder();
  static JsonEncoder jsonEncoder = JsonEncoder();

  @override
  ObservableList<String> fromJSON(dynamic jsonValue,
          [JsonProperty jsonProperty]) =>
      ObservableList<String>.of((jsonValue is String)
          ? jsonDecoder.convert(jsonValue).cast<String>()
          : jsonValue);

  @override
  dynamic toJSON(dynamic object, [JsonProperty jsonProperty]) {
    final ObservableList<String> ols = object;
    return jsonEncoder.convert(ols.toList());
  }
}

@jsonSerializable
class MobX {
  ObservableList<String> mailingList = ObservableList<String>();

  MobX(this.mailingList);
}

    test("Custom ObservableList<String> converter", () {
      // given
      final String json =
          '''{"mailingList":"[\\"aa@test.com\\",\\"bb@test.com\\",\\"cc@test.com\\"]"}''';
      MobX m = MobX(ObservableList<String>.of(
          ['aa@test.com', 'bb@test.com', 'cc@test.com']));
      // when
      JsonMapper.registerConverter<ObservableList<String>>(
          ObservableListStringConverter());
      final String targetJson = JsonMapper.serialize(m, '');
      final MobX instance = JsonMapper.deserialize(targetJson);
      // then
      expect(targetJson, json);
      expect(instance, TypeMatcher<MobX>());
      expect(instance.mailingList, TypeMatcher<ObservableList<String>>());

      JsonMapper.registerConverter<ObservableList<String>>(defaultConverter);
    });
```

BTW, now you owe me a ⭐️

**Comment by felipeleon73** [comment]
A great ⭐️!

**Comment by felipeleon73** [comment]
The proposed solution, however, presents a problem.
The ObservableList is not serialized as a standard list, and this creates problems with any webapi.
A better solution is to recognize the ObservableList as Iterable, modifying the file json_mapper.dart at lines 662-664 as follows:
```
bool get isIterable {
  return isList || isSet || ypeName.indexOf ("ObservableList <") == 0;
}
```
In this way it is enough to use a valueDecorator:
`JsonMapper.registerValueDecorator <ObservableList <String>> ((value) => ObservableList <String> .of (value.cast <String> ()));`

Would it be possible to implement a way (perhaps a JSonProperty) to indicate that an object is Iterable without relying on the name?

**Comment by k-paxian** [comment]
@felipeleon73 Indeed, haven't noticed it myself. Thank you for vanishing it out.

Although, Thanks to your hint above I've got even better approach ironed out in my mind.

I'm gonna decouple typeInfo related code out of this library, this will opens the door for a range of specific "adapter" libraries one per each popular use case. 

- MobX, https://github.com/k-paxian/dart-json-mapper-mobx
- Fixnum, https://pub.dev/packages/fixnum
- etc.

Each adapter library will contain a bundle of pre-configured:

- custom converters
- custom typeInfo providers
- custom value decorators

So in essence you'll have to throw in another library dependency + 1 line of code,
and you are ready to jet 🚀 

```yaml
dependencies:
  dart_json_mapper: any
  dart_json_mapper_mobx: any
```

**Comment by felipeleon73** [comment]
Wow!!!

**Comment by k-paxian** [comment]
@felipeleon73 

Here you are https://github.com/k-paxian/dart-json-mapper-mobx, please check it out, 
contributions are highly welcomed 👍

**Comment by 1N50MN14** [comment]
Hi @k-paxian thanks for supporting mobx!

Bumping mobx from `^0.3.9` to latest `^0.4.0+1` I'm now getting the following error:

`Because dart_json_mapper_mobx 1.0.0 depends on mobx ^0.3.10 and no versions of dart_json_mapper_mobx match >1.0.0 <2.0.0, dart_json_mapper_mobx ^1.0.0 requires mobx ^0.3.10.`

Would it be possible to update pubspec mobx version?

Thank you ;)

**Comment by k-paxian** [comment]
@1N50MN14  done.

**Comment by 1N50MN14** [comment]
@k-paxian thank you!
