### ISSUE TITLE
ignoreNullMembers seems to break the deserialization

### ISSUE THREAD

**Issue by fasterlars** [k-paxian/dart-json-mapper#202]
I have a problem with the ignoreNullMembers annotation. As far as I understand, you can use this annotation if you would like to ignore null members or not existing json members of the json that is about to be deserialized.

I have two models, with the only difference being this annotation:

```
@JsonSerializable()
@Json(caseStyle: CaseStyle.pascal)
class TestModel1 {
  String id = '';
  String? address = '';
}

```
```
@JsonSerializable()
@Json(ignoreNullMembers: true)
@Json(caseStyle: CaseStyle.pascal)
class TestModel2 {
  String id = '';
  String? address = '';
}
```

Now if I parse the exact same data where none if the properties are null, to each model, I would expect the same result. But this is not the case:

![image](https://user-images.githubusercontent.com/42839536/201343256-bf82a7c9-d08f-41e9-b6a7-40c32ebb6177.png)

Every property in TestModel2 is empty strings (their default value). 
![image](https://user-images.githubusercontent.com/42839536/201343322-086ad7ec-71c2-4b08-b067-e14d4c2a75f4.png)

![image](https://user-images.githubusercontent.com/42839536/201343363-67c3947f-bc89-492d-92b5-ad4919c10a52.png)

I would like to use the ignoreNullMembers annotation, but of course also deserialization. So am I doing anything wrong?

**Comment by k-paxian** [comment]
Try to join the two @Json annotations to just one, having both attributes side by side. Intention is to have just one annotation.

**Comment by fasterlars** [comment]
Aaah, rookie mistake, I did not know that you could join the annotations.

Thanks 👍
