### ISSUE TITLE
`main.mapper.g.dart` is not generating all `@jsonSerializable` classes

### ISSUE THREAD

**Issue by jeansebastienZ** [k-paxian/dart-json-mapper#205]
**_Hello @k-paxian !_**

It seems that main.mapper.g.dart is not generating all @jsonSerializable classes.

<img width="276" alt="Capture d’écran 2022-12-12 à 20 14 49" src="https://user-images.githubusercontent.com/65148275/207134478-cada0cbb-133b-4e3f-94c2-385288a823f8.png">

In this folder only **_FieldGroupMDL_** is automatically generated :
```dart
import 'package:dart_json_mapper/dart_json_mapper.dart';
import '../../../engine/utils/wording/identifiers_wording.dart';

import '../abstract_mdls/form_item_mdl.dart';

@jsonSerializable
@Json(discriminatorValue: 'fieldGroup', ignoreNullMembers: true)
class FieldGroupMDL extends FormItemMdl {
  String? icon;
  String? fieldGroupId;
  String? groupParentId;

  FieldGroupMDL({this.icon});

  String getIdentifiers() {
    return IdentifiersWording.fieldGroupMDL;
  }
}

```
For instance , this classe **_TextFieldMdl_** is not generated :
```dart
import 'package:dart_json_mapper/dart_json_mapper.dart';

import '../../../engine/utils/wording/identifiers_wording.dart';
import '../../../engine/utils/enum_classes.dart';
import '../abstract_mdls/field_mdl.dart';

@jsonSerializable
@Json(discriminatorValue: 'fileField', ignoreNullMembers: true)
class FileFieldMdl extends FieldMdl {
  FileType? fileType;
  dynamic mimeType;
  String? fieldGroupId;
  int? maxFiles;

  FileFieldMdl({this.fileType, this.mimeType, this.maxFiles,this.fieldGroupId});

  String getIdentifiers() {
    return IdentifiersWording.fileFieldMdl;
  }
}

```
nor this one :
```dart
import 'package:dart_json_mapper/dart_json_mapper.dart';

import '../../../../engine/utils/wording/identifiers_wording.dart';
import '../abstract_mdls/field_mdl.dart';

@jsonSerializable
@Json(discriminatorValue: 'geoField', ignoreNullMembers: true)
class GeoFieldMdl extends FieldMdl {
  String? lat;
  String? long;
  String? uuid;
  String? fieldGroupId;

  GeoFieldMdl({this.lat, this.long, this.uuid, this.fieldGroupId});

  String getIdentifiers() {
    return IdentifiersWording.geoFieldMdl;
  }
}
```
However if i put the class in an adapter it will be generated :
```dart
 JsonMapper().useAdapter(JsonMapperAdapter(
      valueDecorators: {
        typeOf<Map<String, ValueMdl>>(): (value) =>
            value.cast<String, ValueMdl>(),
        typeOf<List<GeoFieldMdl>>(): (value) => value.cast<GeoFieldMdl>(),
      },
    ));
```

I don't know if it's a path related problem   but i've seen 1 , kinda, equivalent tickets :
https://github.com/k-paxian/dart-json-mapper/issues/87
and it began happen after some structure refacto .

Regards,
Z. Jean-Sébastien

----------------
ps : we can't support you thought sponsoring as it is greyed, is it a bug ?
<img width="383" alt="Capture d’écran 2022-12-12 à 20 39 30" src="https://user-images.githubusercontent.com/65148275/207138973-cb94d409-e7f5-4fa9-aa88-d74fb5ee2e89.png">

**Comment by k-paxian** [comment]
Code is generated only for the used/referenced code, in other words NO code is generated upfront for the dead code which is not referenced anywhere in your main entry point project. 

When you are referencing this class in an adapter, you are creating reference and it means this code is compiled to the app, 
so it generates the stuff inside `main.mapper.g.dart`

If you would like to generate upfront your entire model with all the classes, you can also do that,
take a look at the modular approach example [here](https://github.com/k-paxian/dart-json-mapper/tree/master/models) 

and then you can use it as an adapter in your main project like [this](https://github.com/k-paxian/dart-json-mapper/blob/9ac6d2de3704fb492d5bb984a40f480fe69a8004/perf-test/test/unit/_test.dart#L31)

Probably you could separate your `core` or `core/models` folder as a standalone library project following the modular approach,
then you can re-use this code in different apps, other projects, etc.

as to sponsoring widget have no idea 🤷 is it the same for the "one time" or "monthly" options?

**Comment by jeansebastienZ** [comment]
Oh ok thanks you i see ! 

ps : Yes for the sponsoring look the video below , i can't either "one time" or "monthly" .
https://user-images.githubusercontent.com/65148275/207164681-eef8ecf8-6689-4713-9b8c-ebb541f4aee8.mov

**Comment by k-paxian** [comment]
@jeansebastienZ 
well, I've added few tiers, both monthly and one-time. It seems github changed the way it works, so I don't have any tiers defined. Previously there was an option to custom amount "one-time" 🤷‍♂️ even if you don't have predefined tiers.

Can I treat this issue as resolved then?

**Comment by jeansebastienZ** [comment]
Their tools is totally f*cked up. Can't pay directly ( their payment process does not work ) and can't connect my Paypal account , it's loading ad vitam eternam .
Do you get paypal account ? It will be faster to sponsor you directly it seem ... I wanted my sponsor logo tho 😭 .

**Comment by k-paxian** [comment]
At least they gave you a badge 😄  nice done
![image](https://user-images.githubusercontent.com/18071010/207413799-b72f2945-877b-443a-bba8-230ed7df8cf1.png)
it's not a bug, it's a feature, like MS Access in the good old days: "You've changed 0 rows, are you sure you wanna save?"

well, you can paypal me then, https://www.paypal.me/alexanderMazuruk

**Comment by jeansebastienZ** [comment]
Wtf Github is doing 😂 .

Sent men , thanks you for your hard work on this package.
