### ISSUE TITLE
Dart Json Mapper looks like don't generate valueDecorators when models in different package

### ISSUE THREAD

**Issue by Shader-Killer** [k-paxian/dart-json-mapper#216]
I have a dart package contains my models, everything works fine, except generate generic class valueDecorators.
If model in the same package with **generate_for** dart file, valueDecorators will appear.
If I move model, valueDecorators will disappear, it's an empty array.

**Comment by k-paxian** [comment]
You are probably interested in a multi-project setup. There should be a good doc on how to configure it 😄 
but unfortunately it's not there yet. Anyway, you could learn from [example ](https://github.com/k-paxian/dart-json-mapper/issues/189#issuecomment-1154169441) how to set it up. Here is another [example](https://github.com/k-paxian/dart-json-mapper/blob/aa6c3aafe5cf458ea3b136da8934c09173183d7b/perf-test/test/unit/_test.dart#L31)
