### ISSUE TITLE
Default discriminatorValue may not work.

### ISSUE THREAD

**Issue by rxvincent** [k-paxian/dart-json-mapper#217]
Line 224-228 in mapper.dart from version 2.2.9. It seems that code would never run when discriminatorValue is null, which make the default value of discriminatorValue is always null.

**Comment by k-paxian** [comment]
Can you illustrate your case with the falling unit test please? That way it would be more productive and fast to correct

**Comment by rxvincent** [comment]
I have a base class with below statement

```dart
@jsonSerializable
@Json(discriminatorProperty: 'type')
abstract class BaseAction {
  String? type;
}
```

and then I have a class implement
```dart
@jsonSerializable
class ShowRectangleAction extends BaseAction {
  // properties
}
```

Serialize has no error but when I try to deserialize previous serialized json string. It lead to a JsonMapperSubtypeError error.

In my case, all validDiscriminators is null.

**Comment by rxvincent** [comment]
In mapper.dart when deserialize, method `_detectObjectType` need to find a Type from `_discriminatorToType` map. Here, the `discriminatorValue` can get a correct class name. But the question is in`_discriminatorToType`. I can only find there is one method to update this map is `_updateInternalMaps()`.  And only those class with `jsonMeta.discriminatorValue != null` would trigger `_discriminatorToType.putIfAbsent` to update this map.
