### ISSUE TITLE
Empty Reflectable file - regarding 

### ISSUE THREAD

**Issue by SwathiSankar03092000** [k-paxian/dart-json-mapper#221]
I have this version, 
Flutter 3.13.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision e1e47221e8 (5 weeks ago) • 2023-08-22 21:43:18 -0700
Engine • revision b20183e040
Tools • Dart 3.1.0 • DevTools 2.25.0

when it tries to use the dart_json_mapper: 2.2.9 package it does not generate the code inside the main.reflectable.dart. 
Are there any changes made in the latest update? If so provide me the solution for this. 
Thanks in advance!!

**Comment by k-paxian** [comment]
It's hard to understand. Can you please elaborate more details. Or simple reproduction case.
