### ISSUE TITLE
dart_json_mapper 2.2.10 depends on analyzer ^5.4.0

### ISSUE THREAD

**Issue by matt-hall-zory** [k-paxian/dart-json-mapper#222]
analyzer is currently at version 6.4.0 while dart_json_mapper depends on ^5.4.0.
This has made it impossible to keep riverpod up to date (which depends on ^6.0.0).
Any chance of upgrading the dependency on analyzer to at least 6.0.0?

**Comment by k-paxian** [comment]
Unfortunately it depends on reflectable library from Google which is not up to date with the latest analyzer.

**Comment by matt-hall-zory** [comment]
Ah yes. There is a PR for this in review.
https://github.com/google/reflectable.dart/pull/326

**Comment by matt-hall-zory** [comment]
Reflectable has been updated to 4.0.6
https://pub.dev/packages/reflectable

**Comment by k-paxian** [comment]
Awesome, thanks for letting me know. I'll try to keep up shortly

**Comment by k-paxian** [comment]
Should be there, let me know if anything else needed 😉

**Comment by matt-hall-zory** [comment]
Thanks, but I still can't resolve. Similar issue to what happened in reflectable. I use integration_test which is lagging.
`Because every version of integration_test from sdk depends on meta 1.11.0 and dart_json_mapper >=2.2.11 depends on meta ^1.12.0, integration_test from sdk is incompatible with dart_json_mapper >=2.2.11.`

**Comment by k-paxian** [comment]
In such cases when version discrepancy is not critical, you could temporarily use  https://dart.dev/tools/pub/dependencies#dependency-overrides 

like 
```yaml
...
dependency_overrides:
  meta: '1.11.0'
```

OR youse mapper `2.2.12+1` version where I've downgraded meta package requirement
