### ISSUE TITLE
Wrong targeted data when parsing 

### ISSUE THREAD

**Issue by longbkiter07** [k-paxian/dart-json-mapper#25]
Hi, 
I have a special case:

```
@jsonSerializable
class A {
  @JsonProperty(name: "content")
  B content;
}

@jsonSerializable
class B {
  @JsonProperty(name: "content")
  List<A> content;
}
```
When I parse a json like: 
```
{
      content: {
           content: []
      }
}
```
I expect to have A as a root object. But there is an error that it use B's content as A's content. 
After debugging, I've realized that here is the problem:
```
dynamic getPropertyValue(String name) {
    dynamic result;
    _isPathExists(_getPath(name), (m, k) {
      result = (m is Map && m.containsKey(k)) ? m[k] : m;
    });
    return result;
  }
```
To fix it, should it only be:
```
result = m;
```
? (Because `m[k]` is B's content). 

Thank you

**Comment by k-paxian** [comment]
@longbkiter07 Thank you for letting me know. Could you please figure out a unit test for your cases? This will help a lot.

**Comment by k-paxian** [comment]
ok, I have figured that out on my own. Thank you for your time debugging 👍

**Comment by longbkiter07** [comment]
Thank you for fixing it quickly. It is so helpful for me as it was blocking me.
