### ISSUE TITLE
Too many positional arguments on reflectable-2.2.1

### ISSUE THREAD

**Issue by bounty1342** [k-paxian/dart-json-mapper#26]
Hi, 

I got this error message that seems related to a dependency :

```
[SEVERE] Failed to snapshot build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
[SEVERE] ../../flutter/.pub-cache/hosted/pub.dartlang.org/reflectable-2.2.1/lib/src/builder_implementation.dart:5207:46: Error: Too many positional arguments: 0 allowed, but 1 found.Try removing the extra positional arguments.  InterfaceType get type => InterfaceTypeImpl(this);                                             ^../../flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.4/lib/src/dart/element/type.dart:705:3: Context: Found this candidate, but the arguments don't match.  InterfaceTypeImpl({  ^^^^^^^^^^^^^^^^^../../flutter/.pub-cache/hosted/pub.dartlang.org/reflectable-2.2.1/lib/src/builder_implementation.dart:5214:24: Error: Too many positional arguments: 0 allowed, but 1 found.Try removing the extra positional arguments.      InterfaceTypeImpl(this);                       ^../../flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.4/lib/src/dart/element/type.dart:705:3: Context: Found this candidate, but the arguments don't match.  
InterfaceTypeImpl({  ^^^^^^^^^^^^^^^^^
pub finished with exit code 78
```

Overiding the dependency :
dependency_overrides:
  reflectable: 2.2.0

```[INFO] Running build completed, took 7.7s```

Any idea why ?

Thanks

**Comment by k-paxian** [comment]
Thanks for noticing that, I've got the same stuff yesterday, need to investigate.

**Comment by k-paxian** [comment]
@bounty1342 

My observations so far:

On my Windows laptop, 
* dart 2.7.0
* reflectable: ^2.2.1
Everything is green 💚 

On latest ubuntu Github actions runner
* dart 2.7.0
* reflectable: ^2.2.1
Failure happens 🔴 

On pub.dev pana analysis
* dart 2.7.0
* reflectable: ^2.2.1
Failure happens 🔴 

![image](https://user-images.githubusercontent.com/18071010/72048739-c2679f00-32bd-11ea-9cfc-2f23661f7e98.png)

So my assumption, you are not on Windows?

So the resolution would be to downgrade to `reflectable: 2.2.0`

**Comment by bounty1342** [comment]
Hi,

Actually I use Windows 10 also. 
IDE is Visual Studio Code and the build method run with powershell.

If I understand correctly, the issue is more on reflectable side ?

Regards,

**Comment by k-paxian** [comment]
@bounty1342 
Exactly, it looks like some of "reflectable" library dependencies, has an update and is not yet settled down. Until then we'll use previous version.

**Comment by bounty1342** [comment]
Open an issue on their github, if you like to follow :
https://github.com/dart-lang/reflectable/issues/194

Thanks
