### ISSUE TITLE
could not generate main.reflectable.dart and need a simple mobx example

### ISSUE THREAD

**Issue by deadsoul44** [k-paxian/dart-json-mapper#27]
Hello,

Thanks for the great library, 

I couldn't generate main.reflectable.dart file. I tried to follow the basic setup. I pasted all the additional code in my main.dart file and run the command `pub run build_runner build`. I get the following error:

`'pub' is not recognized as an internal or external command,
operable program or batch file.
`

`flutter pub run build_runner build` command works but it does not generate main.reflectable.dart file.

Besides, I need a very simple mobx example with a separate store. I am especially interested in very nested json deserialization. This could be used for example json: https://jsonplaceholder.typicode.com/posts

I already starred the repo. Thank you very much in advance.

**Comment by k-paxian** [comment]
Hey, welcome!
Things to check
* Make sure your `build.yml` has listed your main.dart
* Make sure your Dart code has at least one class annotated with `@jsonSerializable`

**Comment by deadsoul44** [comment]
It is working now. There was a trivial error in build.yaml file. Thank you again.

**Comment by pavanpodila** [comment]
I am having a similar issue here. Inspite of a correct `build.yml` and having a `@jsonSerializable`, nothing gets generated during the build process.

**Comment by k-paxian** [comment]
Well, there should be something different in a setup. Since latest lib version is built successfully on GitHub actions, including unit tests.

**Comment by pavanpodila** [comment]
This is the class I'm trying to serialize. Not sure why it is not getting picked up. Rest of the setup is as outlined in the docs.

```dart
@jsonSerializable
class FeedItem = _FeedItem with _$FeedItem;

@jsonSerializable
abstract class _FeedItem with Store {
  _FeedItem({this.message, this.user, this.timestamp, this.type});

  final String message;
  final String user;
  final String type;
  final DateTime timestamp;
}

```

**Comment by k-paxian** [comment]
Can you please setup a sample repository to replicate the issue, this will surely speeds up resolution.

At the moment I don't see anything suspicious.

**Comment by bounty1342** [comment]
@pavanpodila, can you try to reference/instanciate a Feeditem() somewhere in your project and relaunch the build. Does it change anything ?

May have encounter this also. Should be easy enough to replicate if that the case.

**Comment by pavanpodila** [comment]
Nothing changes even when it is referenced 😟

**Comment by kwaak** [comment]
> This is the class I'm trying to serialize. Not sure why it is not getting picked up. Rest of the setup is as outlined in the docs.
> 
> ```dart
> @jsonSerializable
> class FeedItem = _FeedItem with _$FeedItem;
> 
> @jsonSerializable
> abstract class _FeedItem with Store {
>   _FeedItem({this.message, this.user, this.timestamp, this.type});
> 
>   final String message;
>   final String user;
>   final String type;
>   final DateTime timestamp;
> }
> ```

Try changing `class FeedItem = _FeedItem with _$FeedItem;` to `class FeedItem extends _FeedItem with _$FeedItem {}`

And check if it does appear in your `main.reflectable.dart` after running the build runner.

**Comment by pavanpodila** [comment]
Tried that, but still doesn't seem to generate the `main.reflectable.dart` file. I'll see if I can take some time out to create a repro

**Comment by k-paxian** [comment]
@pavanpodila Here is the minimal working repo with your case. 
https://github.com/k-paxian/dart-json-mapper-mob-x-integration
Hope this will be useful.

**Comment by pavanpodila** [comment]
Thanks @k-paxian ! I'll see what I'm doing different in my repo. Looks like an env issue at my end.

**Comment by nrehm** [comment]
@pavanpodila What was the solution that got it working?
Currently running into the same problem cant generate the main.reflectable.dart but get correctly generated ones for my test files.
