### ISSUE TITLE
How to register List of List

### ISSUE THREAD

**Issue by deadsoul44** [k-paxian/dart-json-mapper#29]
Hello,

Thank you again for the great package.

I have a list of list coming from API as in the following picture. 

![image](https://user-images.githubusercontent.com/31016182/73772868-4f006280-4781-11ea-9e71-cab7d842646c.png)

I couldn't register the type. I get the following error. 

```
E/flutter (30766): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<dynamic>'
E/flutter (30766): #0      JsonMapper.deserializeObject (package:dart_json_mapper/src/mapper.dart:475:21)
E/flutter (30766): #1      JsonMapper.deserializeObject.<anonymous closure> (package:dart_json_mapper/src/mapper.dart:478:26)
E/flutter (30766): #2      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
```

How can I register a list of lists of objects?

**Comment by k-paxian** [comment]
Hello @deadsoul44 ,

General answer to this kind of cases is a custom converter, but if you'll provide a JSON sample fragment in a text representation, which illustrates the issue I could probably think about making an example converter for you.

**Comment by k-paxian** [comment]
@deadsoul44 please consult with my last commit, it contains unit test with your use case configuration.
Good luck!

**Comment by deadsoul44** [comment]
It works! Thank you very much.
