### ISSUE TITLE
Add capability to iterate model class fields

### ISSUE THREAD

**Issue by deadsoul44** [k-paxian/dart-json-mapper#31]
I have to iterate model class fields to access them with index in ListView.builder. It can be done using mirrors or reflectable as in the following SO post but I wonder if it is possible to do it with dart_json_mapper?

https://stackoverflow.com/questions/17021327/how-do-i-get-all-fields-for-a-class-in-dart

Thank you again!

**Comment by k-paxian** [comment]
I guess you could convert your model class to json and iterate over json properties no?

**Comment by deadsoul44** [comment]
Currently, I have some other problems and not able to test converting to json and try iterating. But it seems to be possible. We can close this for now. Thank you very much again.
