### ISSUE TITLE
Global Settings

### ISSUE THREAD

**Issue by HerrNiklasRaab** [k-paxian/dart-json-mapper#35]
Hello,

is there a way to for example to set `ignoreNullMembers`to `true` for the whole project? Or was it a design decision to don't have a global configuration?

Best,

Niklas

**Comment by k-paxian** [comment]
We could definitely put this flag as part of serialization / deserialization options objects. And it will be possible to create one instance of options object and pass it to each call to JSON mapper. It's virtually the same global options mechanism.

**Comment by HerrNiklasRaab** [comment]
Awesome! Could you publish a new version?
