### ISSUE TITLE
Serialization issue with 2 of the same object

### ISSUE THREAD

**Issue by bounty1342** [k-paxian/dart-json-mapper#36]
Hi,

User user = User();
    Device d = Device(uuid: Uuid());
    user.devices = [];
    user.devices.add(d);
    user.devices.add(d);
    print(JsonMapper.serialize(user));

This genrerate a serialization error :
`E/flutter (31538): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method '&' was called on null.
E/flutter (31538): Receiver: null
E/flutter (31538): Tried calling: &(4294967295)
E/flutter (31538): #0 Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter (31538): #1 new Color (dart:ui/painting.dart:107:42)
E/flutter (31538): #2 WidgetConfigurationModel.backgroundColor
package:easivio/…/models/widget_configuration_model.dart:23
E/flutter (31538): #3 _data.
package:easivio/main.reflectable.dart:3587
E/flutter (31538): #4 _InstanceMirrorImpl.invokeGetter
package:reflectable/src/reflectable_builder_based.dart:340
E/flutter (31538): #5 JsonMapper.enumeratePublicFields
package:dart_json_mapper/src/mapper.dart:287
E/flutter (31538): #6 JsonMapper.serializeObject
package:dart_json_mapper/src/mapper.dart:453
E/flutter (31538): #7 JsonMapper.serializeObject.
package:dart_json_mapper/src/mapper.dart:464
E/flutter (31538): #8 JsonMapper.enumeratePublicFields
package:dart_json_mapper/src/mapper.dart:298
E/flutter (31538): #9 JsonMapper.serializeObject
package:dart_json_mapper/src/mapper.dart:453
E/flutter (31538): #10 JsonMapper.serializeObject.
package:dart_json_mapper/src/mapper.dart:420
E/flutter (31538): #11 MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
E/flutter (31538): #12 ListIterable.toList (dart:_internal/iterable.dart:221:19)
E/flutter (31538): #13 JsonMapper.serializeObject
package:dart_json_mapper/src/mapper.dart:420
E/flutter (31538): #14 JsonMapper.serializeObject.
package:dart_json_mapper/src/mapper.dart:464
E/flutter (31538): #15 JsonMapper.enumeratePublicFields
package:dart_json_mapper/src/mapper.dart:298
E/flutter (31538): #16 JsonMapper.serializeObject
package:dart_json_mapper/src/mapper.dart:453
E/flutter (31538): #17 JsonMapper.serializeObject.
package:dart_json_mapper/src/mapper.dart:464
E/flutter (31538): #18 JsonMapper.enumeratePublicFields
package:dart_json_mapper/src/mapper.dart:298
E/flutter (31538): #19 JsonMapper.serializeObject
package:dart_json_mapper/src/mapper.dart:453
E/flutter (31538): #20 JsonMapper.serializeObject.
package:dart_json_mapper/src/mapper.dart:420
E/flutter (31538): #21 MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
E/flutter (31538): #22 ListIterable.toList (dart:_internal/iterable.dart:221:19)
E/flutter (31538): #23 JsonMapper.serializeObject
package:dart_json_mapper/src/mapper.dart:420
E/flutter (31538): #24 JsonMapper.serializeObject.
package:dart_json_mapper/src/mapper.dart:464
E/flutter (31538): #25 JsonMapper.enumeratePublicFields
package:dart_json_mapper/src/mapper.dart:298
E/flutter (31538): #26 JsonMapper.serializeObject
package:dart_json_mapper/src/mapper.dart:453
E/flutter (31538): #27 JsonMapper.serialize
package:dart_json_mapper/src/mapper.dart:63
E/flutter (31538): #28 User.toJson
package:easivio/…/models/user_model.dart:72
E/flutter (31538): #29 UserRepositories.updateUser
package:easivio/…/repositories/user_repositories.dart:60
E/flutter (31538): #30 UserService.updateUser
package:easivio/…/services/user_service.dart:170
E/flutter (31538): #31 UserService.broadcastPlayListOnDevice
package:easivio/…/services/user_service.dart:166
E/flutter (31538): #32 _DevicePlayListViewState.selectPlayList
package:easivio/…/playlist/device_playlist_view.dart:44
E/flutter (31538): #33 _PlayListBottomBarState.selectPlayList
package:easivio/…/widgets/playlist_bottom_bar.dart:25
E/flutter (31538): #34 _PlaylistSelectionCardState.build.
package:easivio/…/widgets/playlist_selection_card.dart:30
E/flutter (31538): #35 _InkResponseState._handleTap
package:flutter/…/material/ink_well.dart:706
E/flutter (31538): #36 _InkResponseState.build.
package:flutter/…/material/ink_well.dart:789
E/flutter (31538): #37 GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:182
E/flutter (31538): #38 TapGestureRecognizer.handleTapUp
package:flutter/…/gestures/tap.dart:486
E/flutter (31538): #39 BaseTapGestureRecognizer._checkUp
package:flutter/…/gestures/tap.dart:264
E/flutter (31538): #40 BaseTapGestureRecognizer.acceptGesture
package:flutter/…/gestures/tap.dart:236
E/flutter (31538): #41 GestureArenaManager.sweep
package:flutter/…/gestures/arena.dart:156
E/flutter (31538): #42 GestureBinding.handleEvent (package:flutter/src `

Let me know if you need more information.

**Comment by k-paxian** [comment]
Should be fixed now as of `1.5.2`, please let me know if it's not. Thanks for raising this.

**Comment by bounty1342** [comment]
Thanks @k-paxian, reactive as always.
Fix implemeted and tested on our side with positives results. 👍
