### ISSUE TITLE
using deep nested collections at dart_json_mapper_mobx

### ISSUE THREAD

**Issue by rsurkin** [k-paxian/dart-json-mapper#44]
I can't guess what I'm doing wrong, here is my json
```json
[
  {
    "title": "Salads & Dips",
    "items": [
      {
        "id": "1",
        "title": "Columbia Salad",
      }
    ]
  }
]
```
and mobx stores

```dart
@jsonSerializable
class MenuSectionStore extends _MenuSectionStore with _$MenuSectionStore {

}

abstract class _MenuSectionStore with Store {
  @observable
  String title = '';

  @observable
  @JsonProperty(ignoreIfNull: true)
  ObservableList<MenuItemStore> items = ObservableList<MenuItemStore>();
}


@jsonSerializable
class MenuItemStore extends _MenuItemStore with _$MenuItemStore {

}

abstract class _MenuItemStore with Store {
  @observable
  String id;

  @observable
  String title = '';
}

JsonMapper().useAdapter(
      mobXAdapter
    );

// this string is works
JsonMapper.deserialize<MenuSectionStore>(jsonResponse[0]);
// this cause error
JsonMapper.deserialize<ObservableList<MenuSectionStore>>(jsonResponse);
```

errors is 

`
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'MenuItemStore' of 'element'
#0      ObservableList.add (package:mobx/src/api/observable_collections/observable_list.dart)
#1      IterableConverter.fromJSON.<anonymous closure> (package:dart_json_mapper_mobx/dart_json_mapper_mobx.dart:181:57)
#2      List.forEach (dart:core-patch/growable_array.dart:282:8)
#3      IterableConverter.fromJSON (package:dart_json_mapper_mobx/dart_json_mapper_mobx.dart:181:19)
#4      JsonMapper.deserializeObject (package:dart_json_mapper/src/mapper.dart:549:38)
#5      JsonMapper.deserialize (package:dart_json_mapper/src/mapper.dart:46:21)
`

**Comment by k-paxian** [comment]
You should consult with https://github.com/k-paxian/dart-json-mapper#iterable-types first.

And now step by step analysis:

* `ObservableList<MenuItemStore>` is covered because of https://github.com/k-paxian/dart-json-mapper#or-an-easy-case, because there **IS** in advance provided list instance, class field is initialized with an empty list instance:
```dart
@observable
@JsonProperty(ignoreIfNull: true)
ObservableList<MenuItemStore> items = ObservableList<MenuItemStore>();
```

* `ObservableList<MenuSectionStore>` is *not* covered, because there is **NO** in advance provided list instance. So you should provide valueDecorator for that type of list, like this

```dart
JsonMapper().useAdapter(JsonMapperAdapter(
  valueDecorators: {
    typeOf<ObservableList<MenuSectionStore>>(): (value) => value.cast<MenuSectionStore>()
  })
);
```

I hope this helps, let me know otherwise

**Comment by rsurkin** [comment]
but there is another bottleneck, how to use two adapters in same time?  I have to use mobXAdapter, to support ObservableList, but it's not clear to me, if I call useAdapter(A), and then call useAdapter(B),
 is the B will append, or override, adapter, so is this correct?

```dart
JsonMapper().useAdapter(
      mobXAdapter
    );

JsonMapper().useAdapter(JsonMapperAdapter(
  valueDecorators: {
    typeOf<ObservableList<MenuSectionStore>>(): (value) => value.cast<MenuSectionStore>()
  })
);
```

**Comment by k-paxian** [comment]
No troubles here, scroll the https://github.com/k-paxian/dart-json-mapper page to the bottom.

```dart
JsonMapper()
   .useAdapter(fixnumAdapter)
   .useAdapter(mobXAdapter)
   .useAdapter(JsonMapperAdapter(
      valueDecorators: {
        typeOf<ObservableList<MenuSectionStore>>(): (value) => value.cast<MenuSectionStore>()
      }
     ))
   .info(); // print out a list of used adapters to console
```

All adapters are complementary an merged together under the hood

**Comment by rsurkin** [comment]
by your last instructions, i got this errro

```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: type 'CastList<Object, MenuSectionStore>' is not a subtype of type 'ObservableList<MenuSectionStore>'
```

and I've ended by converter

```flutter
typeOf<ObservableList<MenuSectionStore>>(): (value) =>
            ObservableList.of(value).cast<MenuSectionStore>()
```

**Comment by rsurkin** [comment]
thank you for help, patient and library
