### ISSUE TITLE
[Question] Compatibility with Freezed ?

### ISSUE THREAD

**Issue by bounty1342** [k-paxian/dart-json-mapper#45]
All is in the title ;)

Is there a way to define the default serializer to make it compatible with [Freezed](https://pub.dev/packages/freezed#decorators) ? 
Since it support decorator, that should be feasible, what do you think ?

Regards

**Comment by k-paxian** [comment]
Well, for me it's a good question for @rrousselgit. His choice is to integrate with json_serializable. I guess w/o his assistance its not so feasible to me.

If it's a question of having copyWith method? It's totally possible to have it done with JsonMapper.clone method.
