### ISSUE TITLE
Can not serialize Map<String, T>

### ISSUE THREAD

**Issue by hazzo** [k-paxian/dart-json-mapper#46]
Hi is possible to serialize a map of a type?
For example:

```
@jsonSerializable
class Person {
   final int age;
   Person({this.age});
}

Map<String, Person> foo = Map();
foo['bar'] = Person(age: 30);
final json = JsonMapper.serialize(foo);
```

I have been trying this in several ways and I'm not able to get it, but yes I was able to do it with the library `json_serializable`. I thought this one could do the same stuff with less boilerplate.

Thanks!

Edit:
I get this error `It seems your class '_InternalLinkedHashMap<String, Person>' has not been annotated with @jsonSerializable`

**Comment by k-paxian** [comment]
Thank you for vanishing it out, please try new version 1.5.4.
I'm sure you'll not regret about switching from `json_serializable`

**Comment by hazzo** [comment]
I’ll test it as soon as possible. I’m sure you are right. It’s inevitable to tackle every use cases without a bug.

**Comment by hazzo** [comment]
Works like charm! Thnks again

**Comment by hazzo** [comment]
Hi again @k-paxian. I'm sorry to bother you again. But even the fix was working perfectly once I started using mobx-adapter it started bugging again.

If the mobx adapter is not set (`JsonMapper().useAdapter(mobXAdapter);`) works perfect. 

So debugged the lib for a couple of minutes and (not sure if this is the problem) but I discovered that in this line:
```
  TypeInfo getTypeInfo(Type type) {
    var result = TypeInfo(type);
    typeInfoDecorators.values.forEach((ITypeInfoDecorator decorator) {
      result = decorator.decorate(result);
    });
    return result;
  }
```
The mobx adapter appears here (as `MobxTypeInfoDecorator`) so got me thinking that maybe the issue is around that method. Even though the `TypeInfo` has the property `isMap = true` so I'm not completely sure that the problem is here.

If I can help with more info let me know. Thanks!

**Comment by k-paxian** [comment]
Could you please provide an code snippet which is not working for you?

It should have ObservableMap in it, I guess.

**Comment by hazzo** [comment]
Sure but the problem is when serializing a map that is not in mobx. But if I add the adapter to use it with the mobx store the original map which is not in the store breaks with the same error as the one in the beginning of this issue.
Maybe I not explaining my self right.

**Comment by hazzo** [comment]
This works
```
@jsonSerializable
class Person {
  final int age;
  Person({this.age});
}

void main() {
  initializeReflectable();
//  JsonMapper().useAdapter(mobXAdapter);

  Map<String, Person> foo = Map();
  foo['bar'] = Person(age: 30);
  final json = JsonMapper.serialize(foo);
  print(json);
}
```

This does not
```
@jsonSerializable
class Person {
  final int age;
  Person({this.age});
}

void main() {
  initializeReflectable();
  JsonMapper().useAdapter(mobXAdapter);

  Map<String, Person> foo = Map();
  foo['bar'] = Person(age: 30);
  final json = JsonMapper.serialize(foo);
  print(json);
}
```

**Comment by hazzo** [comment]
I discover why it happens, maybe you too already as you wrote de lib 😝 
The issue is in `getTypeInfo` returning a `genericType` of `ObservableMap` even though is not an observable map. Right? 
So this part of code:
```
if (result == null &&
        converters[typeInfo.genericType] != null &&
        getValueDecorator(jsonProperty, typeInfo.type) == null) {
      result = converters[typeInfo.genericType];
    }
```
Does not find the new `Map` adapter you wrote.

**Comment by hazzo** [comment]
This solved for me
```
TypeInfo getTypeInfo(Type type) {
    var result = TypeInfo(type);
    typeInfoDecorators.values.forEach((ITypeInfoDecorator decorator) {
      if (result.genericType == null) {
        result = decorator.decorate(result);
      }
    });
    return result;
  }
```
Don't know if checking if not having a genericType breaks other use cases. But this works for a generic map and also the mobx adpater works for transforming the store to json.

**Comment by k-paxian** [comment]
Thanks for investigation! With the updated versions it should work now.

**Comment by hazzo** [comment]
Cool, thanks!

**Comment by hazzo** [comment]
By the way, tried it and works great. Thanks again
