### ISSUE TITLE
A few Questions

### ISSUE THREAD

**Issue by HerrNiklasRaab** [k-paxian/dart-json-mapper#49]
Hello @k-paxian,

https://codingpassion.net just joined as Encouragement Sponsor! We love the sponsorware approach. This decision was made because we want to commit longterm to this framework. And we will have a lot of questions and requirements in the future. So thank you for that!

A few questions/requirements that came up while developing:
- Is there any way to get support for enums in Lists? For example `List<Color>()`
- Would it be possible to specify `@Json(typeNameProperty: 'typeName')` in `SerializationOptions()` globally?
- Would it be possible to have an option in `SerializationOptions()`, that would serialize/deserialize only properties marked with `@JsonProperty()` and ignores all unmarked?
- Waiting for #38 (HashSet, UnmodifiableListView, UnmodifiableMapView are needed)
- Do sponsors get features marked with "sponsorware" immediately or earlier?

Thanks,

Niklas

**Comment by k-paxian** [comment]
Hello @HerrNiklasRaab 

I'm  really grateful for your trust and your hope for the better future for this project.

> Is there any way to get support for enums in Lists? For example `List<Color>()`

I'll let you know after investigation.

> Would it be possible to specify `@Json(typeNameProperty: 'typeName')` in `SerializationOptions()` globally?

Yep, I'm pleased to deliver your first feature request, `Global typeNameProperty`, it will be accessible in the next release with the `process @JsonProperty annotated fields only ` option.

> Would it be possible to have an option in SerializationOptions(), that would serialize/deserialize only properties marked with @JsonProperty() and ignores all unmarked?

Yes, in the next release.

> Waiting for #38 (HashSet, UnmodifiableListView, UnmodifiableMapView are needed)

I have no ETA on this, but I'm gonna start working towards.

> Do sponsors get features marked with "sponsorware" immediately or earlier?

Features will be delivered on `first come first served basis` for *all* existing sponsors.

**Comment by k-paxian** [comment]
As of 1.5.6:
 
1. Enums support enhanced for `List, Set, Map`, please consult with the unit tests on configuration examples.
2. Global `typeNameProperty` introduced, allowing to nail down the #50
3. Global `processAnnotatedMembersOnly` flag introduced:

```dart
@jsonSerializable
class ImmutableDefault {
  @JsonProperty(defaultValue: 1)
  final int id;
  final String name;
  final Car car;

  const ImmutableDefault({this.id, this.name, this.car});
}

// given
final instance = ImmutableDefault();

// when
final target = JsonMapper.serialize(instance,
     SerializationOptions(indent: '', processAnnotatedMembersOnly: true));

// then
expect(target, '{"id":1}');
```
#38 is the next in queue 🤓

**Comment by k-paxian** [comment]
As of 1.5.7:

* Collection types (HashSet, UnmodifiableListView, UnmodifiableMapView) covered.

**Comment by HerrNiklasRaab** [comment]
Hey @k-paxian,

as stated here: https://github.com/dart-lang/reflectable/issues/207#issuecomment-614840996, we completely removed code generation from our project.

This means we will no longer support your project. Despite this, I want to thank you for the work you have put into this project and it wasn't the fault of this library, why we stopped using code generation.

Hopefully developer experience will increase for code generation and we can resupport this project.

Thanks @k-paxian,

Niklas

**Comment by k-paxian** [comment]
Thank you for your support and contributions! Hope to see you soon 😄
