### ISSUE TITLE
Deserializing with base type as parameter using @Json(typeNameProperty: ' ') throws exception

### ISSUE THREAD

**Issue by HerrNiklasRaab** [k-paxian/dart-json-mapper#50]
This currently throws the following exception: 

> It seems your class 'User' has not been annotated with @jsonSerializable

But we are never serializing or deserializing the User class itself, only the UserImpl class. The UserImpl class picks up the type from the JSON. So there would be no need to annotate the user class, when Serializer can detect the concret type in the JSON?

```dart
  test('User can be serialized and deserialized', () {
    User user = UserBuilder().build();
    var map = JsonMapper.toMap(user);
    var newUser = JsonMapper.fromMap<User>(map);
  });
```

```dart
abstract class User extends DataModel {
  final Email email;

  User copyWith({
    String id,
    Email email,
  });

  factory User(String id) =  UserImpl.newUser;
}

@Json(typeNameProperty: 'type')
@jsonSerializable
class UserImpl extends DataModel implements User {
  final Email email;

  UserImpl(
      {String id,
      this.email})
      : super(id: id);

  factory UserImpl.newUser(
      String id) {
    return UserImpl(
      id: id,
    );
  }

  @override
  User copyWith(
      {Email email,
      String id}) {
    return UserImpl(
        id: id ?? this.id,
        email: email ?? this.email);
  }
}
```

**Comment by k-paxian** [comment]
The issue is on this line
```dart
var newUser = JsonMapper.fromMap<User>(map);
```
You are about to instantiate `abstract` class `User`, according to the Dart rules you are not eligible to do so. If your intention was to instantiate `UserImpl` it should be like that

```dart
final newUser = JsonMapper.fromMap<UserImpl>(map);
```

OR if you would like to down-cast it to abstract `User`:

```dart
User newUser = JsonMapper.fromMap<UserImpl>(map);
```

The challenge is that we don't know which `User` Implementation to instantiate, if you'll not provide implementation class.

**Comment by HerrNiklasRaab** [comment]
> The challenge is that we don't know which User Implementation to instantiate, if you'll not provide implementation class.

`@Json(typeNameProperty: 'type')` is there to dump the type of the serialized object into the JSON. This might look something like this for user:

```
{
   type: "UserImpl",
   email: "test@test.de"
}
```

If i call now : `var newUser = JsonMapper.fromMap<User>(map);` to deserialize into an object, JsonMapper reads the `Type` from the type property. Which is in this case `UserImpl`. And creates an object of this type. Because `UserImpl` is a subtype of `User` i can call the `var newUser = JsonMapper.fromMap<User>(map);` with the typeargument `User`. This is currently the implemented behaviour. If you add `@jsonSerializable` to the abstract class `User` above test will pass.

If I remove the  `@jsonSerializable` from the abstract class I get the Error:

> It seems your class 'User' has not been annotated with @jsonSerializable

But `User` doesn't need to have the `@jsonSerializable` annotation, because you are internally only reflecting on the `UserImpl` instance.

Are you with me now? :D

**Comment by k-paxian** [comment]
Now it's possible with the "global typeNameProperty feature" mentioned in #49 
Let me know if it's not what you've expected.

```dart
class DataModel {
  String id;
  DataModel({this.id});
}

abstract class AbstractUser extends DataModel {
  final String email;

  AbstractUser copyWith({
    String id,
    String email,
  });

  factory AbstractUser(String id) = UserImpl.newUser;
}

@jsonSerializable
class UserImpl extends DataModel implements AbstractUser {
  @override
  final String email;

  UserImpl({String id, this.email}) : super(id: id);

  factory UserImpl.newUser(String id) {
    return UserImpl(
      id: id,
    );
  }

  @override
  AbstractUser copyWith({String email, String id}) {
    return UserImpl(id: id ?? this.id, email: email ?? this.email);
  }
}

// given
final user = UserImpl(id: 'xxx', email: 'x@x.com');
final options = SerializationOptions(typeNameProperty: '@type');

// when
final map = JsonMapper.toMap(user, options);
final newUser = JsonMapper.fromMap<AbstractUser>(map, options);

// then
expect(map.containsKey('@type'), true);
expect(map['@type'], 'UserImpl');
expect(newUser.id, 'xxx');
expect(newUser.email, 'x@x.com');
```
