### ISSUE TITLE
Add ignore 'implementation_imports'

### ISSUE THREAD

**Issue by bounty1342** [k-paxian/dart-json-mapper#52]
In the generated main.reflectable.dart, I presume the following can be added to reduce the numbers of problems :
`// ignore_for_file: implementation_imports`

Regards

**Comment by k-paxian** [comment]
This should be addressed to reflectable library.

**Comment by bounty1342** [comment]
https://github.com/dart-lang/reflectable/issues/203

**Comment by bounty1342** [comment]
https://github.com/dart-lang/reflectable/pull/204
