### ISSUE TITLE
Unmapped Datetime

### ISSUE THREAD

**Issue by bounty1342** [k-paxian/dart-json-mapper#53]
Hi @k-paxian,

I was afraid you got bored, so I found you a new issue 😂 

My Map (Firebase) has a DateTime field but it's not present on my Model, but JsonMapper still want to deserialize it :
`JsonUnsupportedObjectError (Converting object to an encodable object failed: Instance of 'Timestamp')`

Was able to reproduce it with this exemple :
``` dart 
import 'package:dart_json_mapper/dart_json_mapper.dart';

enum MyColor { black, red }

@jsonSerializable
class MyCarModel {
  const MyCarModel({this.model});

  final String model;

  Map<String, dynamic> toJson() {
    return JsonMapper.toMap(this);
  }
}
```

``` dart 
// given
final Map<String, dynamic> json = <String, dynamic>{
   'model': 'Tesla',
   'DateFacturation': Timestamp(1568465485, 0),
};

// when
final MyCarModel myModel = JsonMapper.fromMap(json);

// then
expect(myModel.model, 'Tesla');
```

Regards

**Comment by k-paxian** [comment]
There is a similar issue for built_value:
https://github.com/google/built_value.dart/issues/543

So I see several options for you on this issue:
* Configure your store to **not** add timestamps to snapshots
   ```dart
    await _firestore.settings(timestampsInSnapshotsEnabled: false);
   ```
* You can introduce your own [custom converter](https://github.com/k-paxian/dart-json-mapper#custom-types) on `cloud_firestore` `Timestamp` type
* Support me by sponsoring to create full blown `firestore` adapter, including not only `Timestamp` type support, but the rest of other types, for seamless integrations.

**Comment by bounty1342** [comment]
Actually, I was more thinking about a fifth Jackson annotation, to respect "Feature parity with highly popular Java Jackson" :
["@JsonIgnoreProperties(ignoreUnknown = true)"](http://fasterxml.github.io/jackson-annotations/javadoc/2.7/com/fasterxml/jackson/annotation/JsonIgnoreProperties.html)

> So I see several options for you on this issue:
> 
> * Configure your store to **not** add timestamps to snapshots
>   ```dart
>    await _firestore.settings(timestampsInSnapshotsEnabled: false);
>   ```
The field is not a Firestore Timestamps, it's a regular field. Just that the second app only need some of the fields from Firestore.

> * You can introduce your own [custom converter](https://github.com/k-paxian/dart-json-mapper#custom-types) on `cloud_firestore` `Timestamp` type

Custom Converter would need the field to be declare in the Model. This would be very limiting to have a 1:1 mapping. I did try to add the custom converter anyway, but it's ignore if there is no field. 
(That's why, I consider it's an issue, in one case it ignore it, and in the other one, try to use it)

> * Support me by sponsoring to create full blown `firestore` adapter, including not only `Timestamp` type support, but the rest of other types, for seamless integrations.

Unfortunately, that not plan at the moment to be honest.


Regards

**Comment by k-paxian** [comment]
> Custom Converter would need the field to be declare in the Model. 

Nope, it's not required. You could apply custom adapter freely and keep your class as is.

But you are right! If Jackson has it, here you go, since version 1.5.9:

```dart
      // when
      final myModel = JsonMapper.fromMap<MyCarModel>(
          json, SerializationOptions(ignoreUnknownTypes: true));
```
