### ISSUE TITLE
[MobX adapter] ObservableMap deserialization not working

### ISSUE THREAD

**Issue by ZeBigDuck** [k-paxian/dart-json-mapper#55]
Hi! I have issue with ObservableMap deserialization. Values of the Map are not deserialized but returns instead a `_InternalLinkedHashMap<String, dynamic>`.

Here are my models :

````dart
@jsonSerializable
class Packaging extends PackagingBase with _$Packaging {
  Packaging({String iri, ObservableMap<String, PackagingTranslation> translations}): super(iri: iri, translations: translations);
}

@jsonSerializable
abstract class PackagingBase with Store {
  PackagingBase({
    this.iri,
    this.packaging
  });

  @JsonProperty()
  @observable
  String iri;

  @JsonProperty()
  @observable
  ObservableMap<String, PackagingTranslation> translations;
}
````
````dart
@jsonSerializable
class PackagingTranslation extends PackagingTranslationBase with _$PackagingTranslation {
  PackagingTranslation({String iri, String name}): super(iri: iri, name: name);
}

@jsonSerializable
abstract class PackagingTranslationBase with Store {
  PackagingTranslationBase({
    this.iri,
    this.name
  });

  @JsonProperty()
  @observable
  String iri;

  @JsonProperty()
  @observable
  String name;
}
````

My json is the following :

````json
{
  "iri": "/packagings/1",
  "translations": {
    "en": { "iri": "/packaging_translations/2", "name": "Bag" },
    "fr": { "iri": "/packaging_translations/1", "name": "Sac" }
  }
}
````

In my `valueDecorators`, I have a `ObservableList` handler as described in the doc, which works as expected (this is an example to illustrate but not currently used in this issue) :
```dart
typeOf<ObservableList<PackagingTranslation>>(): (value) {
  return ObservableList.of(value).cast<PackagingTranslation>();
},
```

And I also added what I expected to support `ObservableMaps` :
```dart
typeOf<ObservableMap<String, PackagingTranslation>>(): (value) {
  return ObservableMap.of(value).cast<String, PackagingTranslation>();
}
```

Deserialization fails with the following error :

```
Unhandled Exception: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'PackagingTranslation' in type cast
```

The value of the Map isn't deserialized as it is with `List`.

Am I doing anything wrong ? Thank you!

**Comment by HerrNiklasRaab** [comment]
I guess you are using Mobox, did you register the Mobox Adapter?

**Comment by ZeBigDuck** [comment]
Hi, yes I did :

```dart
  JsonMapper()
      .useAdapter(mobXAdapter)
      .useAdapter(myAdapter)
      .info()
  ;
```

And I saw ObservableMap converter relies on default MapConverter so I added a `print("Hello from MapConverter.toJson")` in `MapConverter.toJson` to be sure it was called, and it is.

**Comment by k-paxian** [comment]
Unfortunately, for the `ObservableMap` you should build your own full blown [custom converter](https://github.com/k-paxian/dart-json-mapper#custom-types), `valueDecorator` approach is not enough.

Or another workaround is:
```dart
@jsonSerializable
class Packaging {
  String iri;
  ObservableMap<String, PackagingTranslation> translations =
      ObservableMap<String, PackagingTranslation>();
}
```
* Fist you should not provide any constructors for `Packaging` class
* Pre-initialize `translations` field with an empty instance

This way you don't need nor `valueDecorator` nor 'converter' approaches.

BTW,

```dart
@jsonSerializable // this annotation is redundant, and can be freely removed
abstract class PackagingTranslationBase with Store {
  PackagingTranslationBase({
    this.iri,
    this.name
  });

  @JsonProperty() // this annotation is redundant, and can be freely removed
  @observable
  String iri;

  @JsonProperty() // this annotation is redundant, and can be freely removed
  @observable
  String name;
}
```

**Comment by ZeBigDuck** [comment]
Awesome, it works!

I did as you suggested, the much more simple solution to pre-initialize my ObservableMap.
And I cleaned up my models with your advices.

Thank you very much for your fast and clear answer!
