### ISSUE TITLE
Deserialization freezes the UI

### ISSUE THREAD

**Issue by ZeBigDuck** [k-paxian/dart-json-mapper#56]
Hi! Sorry, it's me again,

Now that deserialization works as intended, I tried to setup some simple UI with a loader while I'm waiting the parsed response from my API.

While it's loading, my CircularProgressIndicator freezes.

```dart
      FutureBuilder(
        future: api.getClientApi().getClientCollection(),
        builder: (context, snapshot) {
          if (snapshot.hasData == true) {
            return Text("Loaded");
          }

          return CircularProgressIndicator();
        },
```

I tried to make the deserialization process in a `compute()` function, but as computed functions have to be top level ones, I have an error saying that reflectable has not been initialized yet.

Is there a way to unfreeze my loader while I'm parsing data?

Thank you!

**Comment by k-paxian** [comment]
I guess you should call `initializeReflectable();` inside your compute() have you tried that?

**Comment by ZeBigDuck** [comment]
Hi!

Good suggestion, thank you, but it causes new errors that I don't have outside the `compute()`.
I think I won't go further with your lib and make simples toJson/fromJson functions into my entities...

I think I've got a setup a bit inapropriate to use with it.

Thank you for your time!

**Comment by TypingMonkey** [comment]
@k-paxian I came to this issue because I have experienced the same problem. 
calling `initializeJsonMapper();` (not `initializeReflectable();`) inside the compute function indeed enables the JSONmapping to work and return the objects generated form JSON. Posting this here for future people facing the same issue.
