### ISSUE TITLE
Featurerequest: Typenamehandling

### ISSUE THREAD

**Issue by HerrNiklasRaab** [k-paxian/dart-json-mapper#6]
Sorry for coming up here again :). But...

I am also in a situation where I need to handle something like this:

```dart
@jsonSerializable
abstract class Business {
  String name;
}

@jsonSerializable
class Hotel extends Business {
  int stars;
  Hotel(this.stars);
}

@jsonSerializable
class Startup extends Business {
  int userCount;

  Startup(this.userCount);
}

@jsonSerializable
class Stakeholder {
  String fullName;
  List<Business> businesses;

  Stakeholder(this.fullName, this.businesses);
}

main() {
  var jack = Stakeholder("Jack", <Business>[Startup(10), Hotel(4)]);
  var json = JsonMapper.serialize(jack);
  var jack2 = JsonMapper.deserialize<Stakeholder>(json);
  jack2.businesses[0] is Startup; //Should be true
  jack2.businesses[1] is Hotel; //Should be true
}
```

The serializer should be able to, get the current type, save it in a JSON property, for example, **"$type"**. And can create those types based on the **"$type"** property.

Newtonsoft.NET is handling this very pretty: https://www.newtonsoft.com/json/help/html/SerializeTypeNameHandling.htm

Because you are using a kind of "reflection", and not this complicated code generation JSON stuff, this should be possible right?

If you need any help, I am willing to do, but I've never contributed to an open source project, so you are dealing with a noob :).

Thanks and a happy day,

Niklas

**Comment by k-paxian** [comment]
Hey Niklas,

Suggested solution has been implemented. Please consult the unit tests on how to resolve your use case.

btw, thank you for feedback and really useful edge cases.

**Comment by HerrNiklasRaab** [comment]
Hello @k-paxian,

man, you're faster than light! 🥇 

But I have one question left, would something like this also be possible?

```dart
@jsonSerializable
class CEO<TBusiness extends Business> {
  TBusiness business;
  String fullName;

  CEO(this.fullName, this.business);
}

test(
    "Should dump typeName to json property when"
    " @JsonSerializable(includeTypeName: true)", () {
  // given
  final john = CEO<Startup>("John", Startup(10));

  // when
  final String json = JsonMapper.serialize(john);
  final CEO<Startup> target = JsonMapper.deserialize(json);

  // then
  expect(target.business, TypeMatcher<Startup>());
});
```

Thanks,

Niklas
