### ISSUE TITLE
[Suggestion] Add IAdapter to JsonSerializable

### ISSUE THREAD

**Issue by jiechic** [k-paxian/dart-json-mapper#60]
same object use for one time on list but not on global，can you add custom adapter in JsonSerializable for this json object 

like this

```dart
@JsonSerializable(adapter:JsonMapperAdapter(
    valueDecorators: {
      typeOf<List<NoticeItem>>(): (value) => value.cast<NoticeItem>()
    })
))
class NoticeList {
  NoticeList();

  @JsonProperty(name: 'list')
  List<NoticeItem> list;

  @JsonProperty(name: 'totalItem')
  String totalItem;

  @JsonProperty(name: 'unread_count')
  String unreadCount;
}

@JsonSerializable()
class NoticeItem {
  NoticeItem();

  @JsonProperty(name: 'msg_id')
  String msgId;
}
```

**Comment by k-paxian** [comment]
Interesting, I'll take a look on feasibility.

Unfortunately this is impossible to enreach @jsonSerializable annotation due to reflectable library limitation. And with all that it's totally possible with @Json annotation.

**Comment by jiechic** [comment]
I just saw @json

no matter which annotation is used, it can be solved under the current class without registering to the global is a good solution

**Comment by k-paxian** [comment]
Unfortunately it's not possible to specify closure as a const parameter in annotation, so the static function is the only doable way as of today 😄 

```dart
@jsonSerializable
class NoticeItem {}

@Json(valueDecorators: NoticeList.valueDecorators)
@jsonSerializable
class NoticeList {
  static Map<Type, ValueDecoratorFunction> valueDecorators() =>
      <Type, ValueDecoratorFunction>{
        typeOf<List<NoticeItem>>(): (value) => value.cast<NoticeItem>()
      };

  final List<NoticeItem> list;

  const NoticeList(this.list);
}
```
Enjoy

**Comment by jiechic** [comment]
ths，Good
