### ISSUE TITLE
How to set to field a default value when the value in the json file is null or the pair is not existed in the json file

### ISSUE THREAD

**Issue by AlaaEldeenYsr** [k-paxian/dart-json-mapper#65]
I have here that annotated class 
```dart
@jsonSerializable
class NavbarTab {
  NavbarTab({this.icon, this.title, this.on});
  final String icon;
  final String title;
  final bool on;
}
```
And here is the map to instantiate that class from
```json
{
    "icon": "0xe800",
    "on": true
}
```

The title field in the ```NavbarTab ``` is expected to be null because its pair in the map is not existed, So in that case i need automatically to assign it with a default value.
I tried to do this but no thing happened and the final result still null
```dart
  @JsonProperty(defaultValue: 'car')
  final String title;
```

**Comment by k-paxian** [comment]
Thank you! fixed.

**Comment by AlaaEldeenYsr** [comment]
> Thank you! fixed.

@k-paxian Awesome, It's working well, Thank you very much bro
