### ISSUE TITLE
Customer DateTime Converter

### ISSUE THREAD

**Issue by jiechic** [k-paxian/dart-json-mapper#69]
I Customer DateTime Converter
`class DateTimeConverter extends BaseCustomConverter
    implements ICustomConverter<DateTime>{
...
}`
then user code to init on main
`JsonMapper.instance.configureConverter(DateTimeConverter());`

bug it is not work for me，it use default DateConverter to converter date

i want CustomConverter datetime then network json string datime timezone is service timezone，then local datetime is local timezone

**Comment by jiechic** [comment]
use this is Ok
`JsonMapper.instance.useAdapter(
        JsonMapperAdapter(converters: {DateTime: DateTimeConverter()}));`

**Comment by k-paxian** [comment]
You shouldn't use `JsonMapper.instance` instead please consult with this section:
https://github.com/k-paxian/dart-json-mapper#custom-types

```dart
JsonMapper().useAdapter(JsonMapperAdapter(
  converters: {
    DateTime: DateTimeConverter()
  })
);
```

**Comment by jiechic** [comment]
thx

> You shouldn't use `JsonMapper.instance` instead please consult with this section:
> https://github.com/k-paxian/dart-json-mapper#custom-types
> 
> ```dart
> JsonMapper().useAdapter(JsonMapperAdapter(
>   converters: {
>     DateTime: DateTimeConverter()
>   })
> );
> ```
