### ISSUE TITLE
fromJson<T> returns null

### ISSUE THREAD

**Issue by sjosegarcia** [k-paxian/dart-json-mapper#70]
So I have an object of type `Token`, and when I call fromJson it returns null. I made sure that the data that comes from the server does match the contract of the `Token` type. When following through the code of the package this line returns null `    final converter = getConverter(context.parentMeta, typeInfo.type);`. Is there something that I am missing that is causing it to return null?

```dart
var serializeOption =
    SerializationOptions(indent: '', caseStyle: CaseStyle.Snake);
var deserializeOption = DeserializationOptions(caseStyle: CaseStyle.Camel);
```
```dart
    var response = await dio.post("/token",
        data: FormData.fromMap({"username": email, "password": password}));
    Token tokenData = JsonMapper.fromJson<Token>(response.data, deserializeOption);
```
```dart
import 'package:dart_json_mapper/dart_json_mapper.dart' show jsonSerializable;

@jsonSerializable
class Token {
  final String accessToken;
  final String tokenType;
  Token({this.accessToken, this.tokenType});
}
```

**Comment by k-paxian** [comment]
If you are using `fromJson<T>` method please make sure 
```dart
response.data
```
returns JSON as a **String** type

If it returns a **Map** object which is kinda JSON Object, you should use this method 

`fromMap<T>`
