### ISSUE TITLE
[Problem] Not generate ReflectorData for @jsonSerializable when the annotated class is not imported in main.dart

### ISSUE THREAD

**Issue by ikws4** [k-paxian/dart-json-mapper#72]
Hi, guys!
First, I thank you for this great package, it's awesome.
But I have a problem.

If I just add @jsonSerializable for a class, it'll not generate ReflectorData for this class,
```dart
/// model.dart
@jsonSerializable
class Model{
  final int id;

  const Model(this.id);
}

/// main.dart
import 'main.reflectable.dart';

void main() {
  initializeReflectable();
}

/// main.reflectable.dart
// No output from reflectable, 'package:reflectable/reflectable.dart' not used.
```

But when I import `model.dart` in `main.dart`, it'll works.
Is it an expected behaviour？

**Comment by k-paxian** [comment]
Yes, this is intended behavior. 

If you are not including some code to your project this code is treated as dead code. Thus no point in analyzing unused code.
