### ISSUE TITLE
typeNameProperty only works when base class is in the same file as the subclasses.

### ISSUE THREAD

**Issue by krzysztof-lopacki** [k-paxian/dart-json-mapper#76]
The example presenting the 'typeNameProperty' feature that is available on the project site:

```dart
@jsonSerializable
@Json(typeNameProperty: 'typeName')
abstract class Business {
  String name;
}

@jsonSerializable
class Hotel extends Business {
  int stars;

  Hotel(this.stars);
}
```

works only if Hotel is in the same file as Business.
If one moves Hotel to a separate file the 'typeNameProperty' will be ignored and all items will 'deserialized' to Business.

**Comment by k-paxian** [comment]
Could you please share entire setup you have. 

The issue you are describing is possible only in one case: 
* Your separate file having `abstract class Business` is not linked to your `main.dart`,  exactly as mentioned at #72
