### ISSUE TITLE
Ignore properties by default

### ISSUE THREAD

**Issue by Norbert515** [k-paxian/dart-json-mapper#79]
I have a couple of models which extend classes which I don't own. Right now I'm manually overriding those properties and excluding them form serialization like this:

```dart
  @JsonProperty(ignore: true)
  String get somePropertyFromSuperClass => super.somePropertyFromSuperClass ;
```

Would it be possible to have an option in `@Json()` which ignores all properties by default unless explicitly annotated with a `@JsonProperty`.

Or is there another way of solving this without manually excluding all properties?

**Comment by k-paxian** [comment]
Yes, you can. Here is the unit test

https://github.com/k-paxian/dart-json-mapper/blob/84e54ae76cff48d2ccf326313c1e72b18aff3cce/mapper/test/test.constructors.dart#L336


```dart
final target = JsonMapper.serialize(instance,
          SerializationOptions(indent: '', processAnnotatedMembersOnly: true));
```
You can pass `processAnnotatedMembersOnly` flag to the options

**Comment by k-paxian** [comment]
Or would you like to have an individual overrides for this flag as a part of `@Json(processAnnotatedMembersOnly : true)` annotation?
So you'll be able to pick some of the classes to follow this pattern? and leave all other classes behave as global flag suggests.

**Comment by k-paxian** [comment]
Now you have it, enjoy!

**Comment by Norbert515** [comment]
I didn't know about the global flag, thanks! Haveing the fine-grained control with @Json(processAnnotatedMembersOnly : true) definitely helps with specific classes too though!

Thank you very much for such a quick answer & update! :)
