### ISSUE TITLE
Build runner rebuilds with any change in any file

### ISSUE THREAD

**Issue by AlaaEldeenYsr** [k-paxian/dart-json-mapper#81]
The build runner regenerate the code (rebuilds) with any change in any file, Even if that changes have no thing to do with the annotated classes. This cause to take about some seconds extra with every save to hot reload the app. It would be great if you can make the build runner rebuilds only with changes that is related to the annotated classes like in many other packages.

**Comment by AlaaEldeenYsr** [comment]
Any updates sir @k-paxian ?

**Comment by k-paxian** [comment]
Thank you for a great idea!  
Could you be so kind to test the latest version `1.6.3`
