### ISSUE TITLE
Problem with mapping list of my objects

### ISSUE THREAD

**Issue by michaldev** [k-paxian/dart-json-mapper#83]
Hi. I have a problem with mapping the list of my objects.

Error:
`type 'List<Object>' is not a subtype of type 'List<Photo>'`

My models:
```
@jsonSerializable
class Post {
  int id;

  @JsonProperty(name: 'created_at')
  DateTime createdAt;

  List<Photo> photos = [];
  bool moderated;
  int votes;

  Post({this.id, this.photos, this.moderated, this.votes, this.createdAt});
}
```

```
@jsonSerializable
class Photo {
  int id;
  int votes;
  String url;

  Photo({this.id, this.votes, this.url});
}
```

I parse of the objects like this:
`postsJson.map((json) => JsonMapper.deserialize<Post>(json)).toList();`

This is like your example with vehicles but doesn't work. What is not correct?

**Comment by moneer-muntazah** [comment]
Hi @michaldev,

Checkout the iterable types section in the [docs](https://pub.dev/packages/dart_json_mapper#iterable-types)

Before you call 
```dart
JsonMapper.deserialize
```

do this 

```dart
JsonMapper().useAdapter(JsonMapperAdapter(
  valueDecorators: {
    typeOf<List<Photo>>(): (value) => value.cast<Photo>(),
  })
);
```

**Comment by moneer-muntazah** [comment]
You need an adapter because the value is being passed to the constructor. If it were not you would get away with initializing it with []

**Comment by michaldev** [comment]
> Hi @michaldev,
> 
> Checkout the iterable types section in the [docs](https://pub.dev/packages/dart_json_mapper#iterable-types)
> 
> Before you call
> 
> ```dart
> JsonMapper.deserialize
> ```
> 
> do this
> 
> ```dart
> JsonMapper().useAdapter(JsonMapperAdapter(
>   valueDecorators: {
>     typeOf<List<Photo>>(): (value) => value.cast<Photo>(),
>   })
> );
> ```

This is working, thanks. But this is a weird and not a clean method. In the json_serializable package, it's work automatic.

**Comment by moneer-muntazah** [comment]
> > Hi @michaldev,
> > Checkout the iterable types section in the [docs](https://pub.dev/packages/dart_json_mapper#iterable-types)
> > Before you call
> > ```dart
> > JsonMapper.deserialize
> > ```
> > 
> > 
> > do this
> > ```dart
> > JsonMapper().useAdapter(JsonMapperAdapter(
> >   valueDecorators: {
> >     typeOf<List<Photo>>(): (value) => value.cast<Photo>(),
> >   })
> > );
> > ```
> 
> It works, thanks. But this is a weird and not clean method. In the json_serializable package, it's work automatic.

It depends on how you use the package. I wrap the whole package in a class and expose it through it, and call useAdapter once in beginning of the application.

**Comment by michaldev** [comment]
Yes, You are right 👍
