### ISSUE TITLE
Unnecessary fromJSON invocation when constructor is declared

### ISSUE THREAD

**Issue by moneer-muntazah** [k-paxian/dart-json-mapper#86]
Hi k-paxian,

I hope you are doing well.

This is a question/suggestion. I have a class that I want to make immutable, and make all of its fields final. To do so I have to create a constructor for my final fields to be initialized. Check out this code example:

```dart
import 'package:dart_json_mapper/dart_json_mapper.dart'
    show
        JsonMapper,
        Json,
        jsonSerializable,
        ICustomConverter,
        JsonProperty;
import 'main.mapper.g.dart' show initializeJsonMapper;
import "package:meta/meta.dart";

const myCustomConverter = _MyCustomConverter();

class _MyCustomConverter implements ICustomConverter<String> {
  const _MyCustomConverter();

  @override
  String fromJSON(dynamic jsonValue, [JsonProperty jsonProperty]) {
    print("called");
    if (jsonValue is int) return jsonValue.toString();
    if (jsonValue is String) return jsonValue;
    return null;
  }

  @override
  dynamic toJSON(String object, [JsonProperty jsonProperty]) {
    throw UnimplementedError();
  }
}

@jsonSerializable
@immutable
class User {
  @JsonProperty(name: "id")
  final int id;

  @JsonProperty(name: "type",
    converter: myCustomConverter)
  final String type;

  User(this.id, this.type);

  @override
  String toString() {
    return '''{"id": $id, "type": $type}''';
  }
}

void main() {
  initializeJsonMapper();

  User user = 
  JsonMapper.deserialize('''{"id": 42,  "type": "sudoer"}''');

  print(user);

}
```

The problem is with how many times the fromJSON gets called. My understanding is that if the annotation is on the property and the type is not iterable, fromJSON will be called twice- once to do the conversion and another time to do any kind of modification on the converted value, but in this example because I have declared a constructor fromJSON gets called a third time. 

It seems unnecessary. In this circumstance my only other option is to remove my annotation from the property and put it in the constructor instead in which case I have to change the logic in fromJSON because now it will only be called once.

Is there a way to have finer control over how many times fromJSON gets called? And could you please include some details about this in the documentation.

Thank you  👍

**Comment by k-paxian** [comment]
Hey @moneer-muntazah 

You are absolutely right, since `1.6.5` there will be a cache layer in place for converted values, so converter methods shouldn't be invoked more than once with the same input parameters.

Thank you for pointing this out 👍
