### ISSUE TITLE
naming conflicts in generated file

### ISSUE THREAD

**Issue by moneer-muntazah** [k-paxian/dart-json-mapper#88]
Hi k-paxian,

I've ran across this scenario which forces me to manually comment out imports in main.mapper.g.dart

lib/models/user.dart
```dart
import 'package:dart_json_mapper/dart_json_mapper.dart'
    show
        jsonSerializable;

@jsonSerializable
class User {
  int id;

  @override
  String toString() {
    return '''{"id": $id}''';
  }
}
```

lib/screens/user.dart
```dart
import "../models/user.dart" as model;
import "package:meta/meta.dart";

@immutable
class User {}
```

lib/main.dart
```dart
import 'main.mapper.g.dart' show initializeJsonMapper;
import "screens/user.dart";

void main() {
  initializeJsonMapper();
}
```

It looks like because I annotated User in lib/screens/user.dart with @immutable and referenced my jsonSerializable model in the same file, it gets referenced in main.mapper.g.dart, and causes a naming conflict

Thank you so much for your work. I appreciate it a lot

**Comment by k-paxian** [comment]
Thank you for discovering edge cases ❤️ This is the only way to make this library better.
I'll look into this
