### ISSUE TITLE
Bug in tests: '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Pt'

### ISSUE THREAD

**Issue by ValeriusGC** [k-paxian/dart-json-mapper#9]
Hi!
I got an error with deserializing so i decided test it inside your test themselves.
I added deserializing inside test `test/test.constructors.dart:170` in this way:

```
    String pTargetJson = JsonMapper.serialize(pTarget, '');
    final PtDerived pTargetBack = JsonMapper.deserialize(pTargetJson); // My string
```
and got an error too 
`type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Pt'`

**Comment by ValeriusGC** [comment]
Look in method `Type getDeclarationType(DeclarationMirror mirror)`
Inside it `Type result` has no result at all.
But when in
```
@jsonSerializable
class PtDerived extends Base<Pt> {
  PtDerived(Pt value) : super(value);
}
```
I turn parameter in field like this  
```
@jsonSerializable
class PtDerived extends Base<Pt> {
  final Pt pt;
  PtDerived(this.pt) : super(null);
}
```
all goes well.

**Comment by k-paxian** [comment]
Hey @ValeriusGC 

Indeed, it was a partial implementation of that feature:
https://github.com/k-paxian/dart-json-mapper#inherited-classes-derived-from-abstract--base-class

Now it should be better.

```dart
class Base<T> {
  final T value;

  Base(this.value);
}

@jsonSerializable
@Json(includeTypeName: true)
class Pt {
  Pt();
}

@jsonSerializable
class PtDerived extends Base<Pt> {
  PtDerived(Pt value) : super(value);
}
```

To be short, you should use extra @Json(includeTypeName: true) annotation for derived classes
to make them traversed to/from json smoothly. As a side effect json will contain concrete type information as a separate json property.

```dart
final PtDerived pTarget = PtDerived(Pt());
String pTargetJson = JsonMapper.serialize(pTarget, '');
expect(pTargetJson, '{"value":{"@@type":"Pt"}}');
```

**Comment by ValeriusGC** [comment]
In most cases client does not want to lose this info so why it is made not by default behaviour?

**Comment by k-paxian** [comment]
- Well, for that I could propose some static bool flag `JsonMapper.includeTypeName = true` to make this applied to all classes w/o annotation. In my own use cases, type information is not needed to be leaked to json output.
- You have the point, docs need to be clarified.

**Comment by k-paxian** [comment]
@ValeriusGC 

I'm pleased to let you know. Since version 1.1.9, your use case will not require using `@Json(includeTypeName: true)` annotation.

Type information will be captured from the constructor parameter directly.

**Comment by AlaaEldeenYsr** [comment]
Any updates here? i'm facing the same issue with the package last update 
```type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Map<String, NavbarTab>'```

**Comment by k-paxian** [comment]
@AlaaEldeenYsr please share your code so I could analyze what's wrong

**Comment by AlaaEldeenYsr** [comment]
Alright Here is the class where the issue is coming from and specifically from the tabs filed
```final Map<String, NavbarTab> tabs;```  
```
@jsonSerializable
class NavbarConfig {
  NavbarConfig({this.tabs, this.activeColor, this.inactiveColor, this.backgroundColor, this.fontSize, this.fontWeight});

  final Map<String, NavbarTab> tabs;

  final String activeColor;
  final String inactiveColor;
  final String backgroundColor;
  final double fontSize;
  final FontWeight fontWeight;
}
```
And here is the ```NavbarTab``` class
```
@jsonSerializable
class NavbarTab {
  NavbarTab({this.icon, this.title, this.on});
  final String icon;
  final String title;
  final bool on;
}
```
And here is the json data
```
{
  "navbar": {
    "tabs": {
      "home": {
        "icon": "0xe800",
        "title": "Home",
        "on": true
      },
      "sections": {
        "icon": "0xe801",
        "title": "Sections",
        "on": true
      }
    },
    "active_color": null,
    "inactive_color": null,
    "background_color": null,
    "font_size": null,
    "font_weight": null
  }
}
```
And i deserialize the json file to create instance of the ```NavbarConfig``` class through this line
```JsonMapper.fromMap<NavbarConfig>(GetIt.instance<Config>().config['navbar'])```

and here is the issue
```

════════ Exception caught by widgets library ═══════════════════════════════════
The following _TypeError was thrown building RootWrapper(dirty):
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Map<String, NavbarTab>'

The relevant error-causing widget was
    RootWrapper 
lib\…\navigation.dart\router.gr.dart:20
When the exception was thrown, this was the stack
#0      _data.<anonymous closure>.<anonymous closure> 
package:news/main.reflectable.dart:72
#1      Function._apply  (dart:core-patch/function_patch.dart:12:68)
#2      Function.apply  (dart:core-patch/function_patch.dart:33:12)
#3      ClassMirrorBase.newInstance 
package:reflectable/src/reflectable_builder_based.dart:655
#4      JsonMapper.deserializeObject 
package:dart_json_mapper/src/mapper.dart:685
...
════════════════════════════════════════════════════════════════════════════════
```

I tried to use this but not thing happened 
```
void main() async {
  initializeReflectable();
  JsonMapper().useAdapter(JsonMapperAdapter(
    valueDecorators: {
      typeOf<Map<String, NavbarTab>>(): (value) => value.cast<String, NavbarTab>(),
    },
  ));
```

Please help @k-paxian

**Comment by k-paxian** [comment]
@AlaaEldeenYsr 
Since version `1.5.13` your use case is supported. Thank you for letting me know about this.

Please refer to this commit for more details & unit test code https://github.com/k-paxian/dart-json-mapper/commit/1bf018f653ae477dc7582d9c102e24d8f0ae92ef

**Comment by AlaaEldeenYsr** [comment]
@k-paxian Thank you very much

**Comment by AlaaEldeenYsr** [comment]
@k-paxian 
It worked fine thank you so much.
