### ISSUE TITLE
What if it inherited CaseStyle from the parent serializable class?

### ISSUE THREAD

**Issue by k-paxian** [k-paxian/dart-json-mapper#91]
```dart
@Json(caseStyle: CaseStyle.Snake)
class MyClass {
  final ThirdPartyEnum  myEnum; // my_enum

  /// ...
}

enum ThirdPartyEnum {firstField, secondField} // first_field, second_field
```

**Comment by moneer-muntazah** [comment]
Howdy! k-paxian!

Are you thinking about removing it from `DeserializationOptions`? Or having it as an addition?  Having both might be confusing.

also what about scenarios like these

```dart
@JsonSerializable(caseStyle: CaseStyle.Snake)
class MyClass {
    final another = AnotherClass();
}

@JsonSerializable(caseStyle: CaseStyle.Pascal)
class AnotherClass{}
```

or 

```dart
@JsonSerializable(caseStyle: CaseStyle.Snake)
class MyClass {
    final another = AnotherClass();
}

@JsonSerializable(caseStyle: null)
class AnotherClass{}
```

Will these cause  `AnotherClass` to override the `caseStyle`? If so it would be a useful feature to have. Currently with `DeserializationOptions` You would be stuck with one option. But it would also be unfortunate that you have to pass null to default to not having a `caseStyle`

Personally, I have a somewhat big application that has Magento as a backend, and other services. Magento alone is quit messy with JSON. In all of my models except one I explicitly list JsonProperty on every property. Some of it has to do with issues we have in naming, but I actually like processing annotated members only, and listing the names above the properties. It feels clearer, and less error prone. Albeit more verbose.

**Comment by moneer-muntazah** [comment]
Ohh sorry I didn't realize that you already have it added to JsonSerializble. You were just talking about enums. My bad

**Comment by moneer-muntazah** [comment]
I just realized that we have it with `Json` already. What would be different about adding it in `JsonSerializable`?

**Comment by k-paxian** [comment]
Sorry, inaccurate copy from https://github.com/google/json_serializable.dart/issues/297#issuecomment-626055181

In an essence For Third party enum(which you cannot annotate)  it makes sense to inherit case style from container class and/or global casestyle option from `DeserializationOptions`.

I'm thinking to refactor converter contract for that,  instead of 
```dart
/// Abstract class for custom converters implementations
abstract class ICustomConverter<T> {
  dynamic toJSON(T object, [JsonProperty jsonProperty]);
  T fromJSON(dynamic jsonValue, [JsonProperty jsonProperty]);
}
```

I'd like to be:

```dart
/// Abstract class for custom converters implementations
abstract class ICustomConverter<T> {
  dynamic toJSON(T object, [SerializationContext context]);
  T fromJSON(dynamic jsonValue, [DeserializationContext context]);
}
```

And context would have both meta data's from field level and class level and global options. 
So Enum converter could decide on it's own how to deal with enum values casing.
