### ISSUE TITLE
Deserialization fails when deserializing a map

### ISSUE THREAD

**Issue by caneva20** [k-paxian/dart-json-mapper#96]
Hello @k-paxian!

I'm trying to (de)serialize a `Map<String, bool>`, but while serialization works fine, when I try to deserialize it, it fails saying my enum is missing annotation, although I'm not using an enum.

I'm not sure if this is a bug or if I am doing something wrong.

### Minimum reproducible code:
```dart
void main() {
  initializeJsonMapper();

  var json = JsonMapper.serialize(<String, bool>{
    'foo': true,
    'bar': false,
    'bazz': true,
  });

  //This fails
  var map = JsonMapper.deserialize<Map<String, bool>>(json);
}
```

I even tried using a value decorator, but it didn't seem to help:
```dart
initializeJsonMapper(adapters: [
    JsonMapperAdapter(
      valueDecorators: {
        typeOf<Map<String, bool>>(): (value) => value.cast<String, bool>(),
      },
    ),
  ]);
```

That's the error I'm getting:
```shell
E/flutter (10387): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: It seems your Enum class field is missing annotation:
E/flutter (10387): @JsonProperty(enumValues: null.values)
E/flutter (10387): #0      JsonMapper._deserializeObject (package:dart_json_mapper/src/mapper.dart:798:7)
E/flutter (10387): #1      JsonMapper._configureConverter.<anonymous closure> (package:dart_json_mapper/src/mapper.dart:634:24)
E/flutter (10387): #2      MapConverter.fromJSON.<anonymous closure> (package:dart_json_mapper/src/model/converters.dart:348:31)
E/flutter (10387): #3      MapMixin.map (dart:collection/maps.dart:170:28)
E/flutter (10387): #4      MapConverter.fromJSON (package:dart_json_mapper/src/model/converters.dart:347:25)
E/flutter (10387): #5      JsonMapper._getConvertedValue (package:dart_json_mapper/src/mapper.dart:371:25)
E/flutter (10387): #6      JsonMapper._deserializeObject (package:dart_json_mapper/src/mapper.dart:785:11)
E/flutter (10387): #7      JsonMapper.deserialize (package:dart_json_mapper/src/mapper.dart:62:21)
E/flutter (10387): #8      main (package:redacted/main.dart:43:24)
E/flutter (10387): #9      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)
E/flutter (10387): #10     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (10387): #11     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (10387): #12     _runZoned (dart:async/zone.dart:1630:10)
E/flutter (10387): #13     runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter (10387): #14     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:223:5)
E/flutter (10387): #15     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (10387): #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by caneva20** [comment]
Well, turns out I was a bit of an idiot, I had two adapters, but I thought it didn't matter (it does), it still gives me an error, but it a different one

```shell
E/flutter (10387): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, bool>'
E/flutter (10387): #0      JsonMapper.deserialize (package:dart_json_mapper/src/mapper.dart:62:5)
E/flutter (10387): #1      main (package:online_relief/main.dart:38:25)
E/flutter (10387): #2      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)
E/flutter (10387): #3      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (10387): #4      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (10387): #5      _runZoned (dart:async/zone.dart:1630:10)
E/flutter (10387): #6      runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter (10387): #7      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:223:5)
E/flutter (10387): #8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (10387): #9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

this happens without any adapters, the remaining of the code is the same.

**Comment by k-paxian** [comment]
Indeed, this is not so obvious from the docs I were trying to explain how to do that.

At this very moment you have three options to make this happen
* one is using adapter as you've mentioned above, illustrated here https://github.com/k-paxian/dart-json-mapper/blob/bbd0ab147aef8a404ee6734518c2f40fe56e4a61/mapper/test/test.converters.dart#L228
* second is using [template instance](https://github.com/k-paxian/dart-json-mapper#deserialization-template)
```dart
final target = JsonMapper.deserialize(json, DeserializationOptions(template: <String, bool>{}));
```
* turn this Map to a class field with field [pre-initialization](https://github.com/k-paxian/dart-json-mapper#or-an-easy-case)

**Comment by caneva20** [comment]
Wonderful! Using a template instance solves my problem partially, and to solve it fully I just need to fix a bug in one of my adapters (I have two from a private package).

As this is kinda related, is there any resource (docs or more examples) for **creating** custom adapters? I have one that "exports" an internal type using a `TypeInfoDecorator` that I created based on the three adapters you have and one of them ([this one](https://github.com/k-paxian/dart-json-mapper/blob/bbd0ab147aef8a404ee6734518c2f40fe56e4a61/adapters/fixnum/lib/dart_json_mapper_fixnum.dart#L24)) returns `null` in its default case, because of that I thought it was ok (and it was the easiest to understand), but this is what was causing the first exception that I mentioned. (when I changed to call its `super` on default it fixed the problem btw)

**Comment by k-paxian** [comment]
> is there any resource (docs or more examples) for **creating** custom adapters?

Not yet, all I have is the existing adapters [here](https://github.com/k-paxian/dart-json-mapper/tree/master/adapters)
So the best way as of now is to dig into them 😄 and figure out how it might look like.

The whole adapters concept is not yet stabilized yet, I'm still gathering use cases from issues to make the adapters contract more mature.

**Comment by caneva20** [comment]
Ah, ok that's fair!

I can share the ones I've created, if that's of any help to you, they are quite simple though.

**Comment by k-paxian** [comment]
As of fixnum `TypeInfoDecorator` I should fix that, since literally no one is using it, I've not got any issues related, so it stayed like this returning null happily.

It make sense to share adapters which are reusable across the projects, mostly based on popular 3rd party libraries
