### ISSUE TITLE
Nullsafety support

### ISSUE THREAD

**Issue by aliyazdi75** [k-paxian/dart-json-mapper#97]
`flutter pub get`:
```
Because every version of flutter_localizations from sdk depends on intl 0.17.0-nullsafety.2 and dart_json_mapper 1.7.2 depends on intl ^0.16.1, flutter_localizations from sdk is incompatible with dart_json_mapper 1.7.2.
And because no versions of dart_json_mapper match >1.7.2 <2.0.0, flutter_localizations from sdk is incompatible with dart_json_mapper ^1.7.2.
So, because  depends on both dart_json_mapper ^1.7.2 and flutter_localizations any from sdk, version solving failed.
```

**Comment by aliyazdi75** [comment]
It can be fixed by adding:
```
dependency_overrides:
  intl: ^0.17.0-nullsafety.2
```

**Comment by k-paxian** [comment]
![image](https://user-images.githubusercontent.com/18071010/100549572-f4864480-3273-11eb-9c19-aad57b5b6482.png)
At the moment I'm doing exactly that.
`reflectable` package is not migrated yet, as soon it'll happens I'll proceed with the migration

**Comment by mit-mit** [comment]
Null safety support in reflectable is tracked in https://github.com/google/reflectable.dart/issues/229

**Comment by jiechic** [comment]
> ![image](https://user-images.githubusercontent.com/18071010/100549572-f4864480-3273-11eb-9c19-aad57b5b6482.png)
> At the moment I'm doing exactly that.
> `reflectable` package is not migrated yet, as soon it'll happens I'll proceed with the migration

it is update reflectable 3.0.0-nullsafety.1

**Comment by k-paxian** [comment]
It should be stable, 3.0.0 otherwise it's not ready. At this moment it's only a preview of partial migration.

**Comment by cedvdb** [comment]
stable has been released

**Comment by k-paxian** [comment]
Mapper has been migrated to null safety 🥇, but..., due to [this ](https://github.com/google/reflectable.dart/issues/238) issue, pub.dev doesn't recognize that yet 😞 we are still waiting for the wonder.

**Comment by mapleafgo** [comment]
Hope to provide nullsafety support for `dart_json_mapper_mobx`

**Comment by k-paxian** [comment]
@mapleafgo   ok, I thought no one is using it really

**Comment by mapleafgo** [comment]
> @mapleafgo ok, I thought no one is using it really

It's a very useful tool.

**Comment by buzzware** [comment]
Still waiting for this, even though https://pub.dev/packages/reflectable/changelog says 
"3.0.0 Support null safety in a stable version of reflectable."
This is the last thing holding up my app from null safety.

**Comment by k-paxian** [comment]
@buzzware According to this [issue](https://github.com/dart-lang/pub-dev/issues/4680) all the blame could be addressed towards maintainers of `build_runner_core` which is Google 😄

**Comment by buzzware** [comment]
> @buzzware According to this [issue](https://github.com/dart-lang/pub-dev/issues/4680) all the blame could be addressed towards maintainers of `build_runner_core` which is Google 😄

OK, thanks, I'll draw their attention to it

**Comment by k-paxian** [comment]
![image](https://user-images.githubusercontent.com/18071010/117290355-ffba4d80-ae6d-11eb-8902-8a8354bc0ce9.png)
